/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForRestaurantsRouteImport } from './routes/for-restaurants'
import { Route as ForFarmersRouteImport } from './routes/for-farmers'
import { Route as ForDriversRouteImport } from './routes/for-drivers'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TrackPublicIdRouteImport } from './routes/track.$publicId'
import { Route as RestaurantSettingsRouteImport } from './routes/restaurant.settings'
import { Route as RestaurantRecurringRouteImport } from './routes/restaurant.recurring'
import { Route as RestaurantNotificationsRouteImport } from './routes/restaurant.notifications'
import { Route as RestaurantMessagesRouteImport } from './routes/restaurant.messages'
import { Route as RestaurantMarketplaceRouteImport } from './routes/restaurant.marketplace'
import { Route as RestaurantDashboardRouteImport } from './routes/restaurant.dashboard'
import { Route as RestaurantCompareRouteImport } from './routes/restaurant.compare'
import { Route as RestaurantCheckoutRouteImport } from './routes/restaurant.checkout'
import { Route as RestaurantCartRouteImport } from './routes/restaurant.cart'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as FarmerSettingsRouteImport } from './routes/farmer.settings'
import { Route as FarmerNotificationsRouteImport } from './routes/farmer.notifications'
import { Route as FarmerMessagesRouteImport } from './routes/farmer.messages'
import { Route as FarmerDashboardRouteImport } from './routes/farmer.dashboard'
import { Route as FarmerAnalyticsRouteImport } from './routes/farmer.analytics'
import { Route as DriverVehicleRouteImport } from './routes/driver.vehicle'
import { Route as DriverSettingsRouteImport } from './routes/driver.settings'
import { Route as DriverNotificationsRouteImport } from './routes/driver.notifications'
import { Route as DriverMessagesRouteImport } from './routes/driver.messages'
import { Route as DriverHistoryRouteImport } from './routes/driver.history'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as DriverDashboardRouteImport } from './routes/driver.dashboard'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as RestaurantSuppliersIndexRouteImport } from './routes/restaurant.suppliers.index'
import { Route as RestaurantSettingsIndexRouteImport } from './routes/restaurant.settings.index'
import { Route as RestaurantOrdersIndexRouteImport } from './routes/restaurant.orders.index'
import { Route as RestaurantMessagesIndexRouteImport } from './routes/restaurant.messages.index'
import { Route as RestaurantInvoicesIndexRouteImport } from './routes/restaurant.invoices.index'
import { Route as FarmerStockIndexRouteImport } from './routes/farmer.stock.index'
import { Route as FarmerSettingsIndexRouteImport } from './routes/farmer.settings.index'
import { Route as FarmerRevenueIndexRouteImport } from './routes/farmer.revenue.index'
import { Route as FarmerProductsIndexRouteImport } from './routes/farmer.products.index'
import { Route as FarmerOrdersIndexRouteImport } from './routes/farmer.orders.index'
import { Route as FarmerMessagesIndexRouteImport } from './routes/farmer.messages.index'
import { Route as DriverMissionsIndexRouteImport } from './routes/driver.missions.index'
import { Route as DriverMessagesIndexRouteImport } from './routes/driver.messages.index'
import { Route as AdminValidationsIndexRouteImport } from './routes/admin.validations.index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminDisputesIndexRouteImport } from './routes/admin.disputes.index'
import { Route as RestaurantSuppliersNewRouteImport } from './routes/restaurant.suppliers.new'
import { Route as RestaurantSuppliersSupplierIdRouteImport } from './routes/restaurant.suppliers.$supplierId'
import { Route as RestaurantSettingsTeamRouteImport } from './routes/restaurant.settings.team'
import { Route as RestaurantSettingsSecurityRouteImport } from './routes/restaurant.settings.security'
import { Route as RestaurantSettingsProfileRouteImport } from './routes/restaurant.settings.profile'
import { Route as RestaurantSettingsPaymentsRouteImport } from './routes/restaurant.settings.payments'
import { Route as RestaurantSettingsNotificationsRouteImport } from './routes/restaurant.settings.notifications'
import { Route as RestaurantSettingsEstablishmentRouteImport } from './routes/restaurant.settings.establishment'
import { Route as RestaurantOrdersOrderIdRouteImport } from './routes/restaurant.orders.$orderId'
import { Route as RestaurantMessagesConversationIdRouteImport } from './routes/restaurant.messages.$conversationId'
import { Route as RestaurantMarketplaceProductIdRouteImport } from './routes/restaurant.marketplace.$productId'
import { Route as RestaurantInvoicesInvoiceIdRouteImport } from './routes/restaurant.invoices.$invoiceId'
import { Route as FarmerStockInventoryRouteImport } from './routes/farmer.stock.inventory'
import { Route as FarmerSettingsTeamRouteImport } from './routes/farmer.settings.team'
import { Route as FarmerSettingsSecurityRouteImport } from './routes/farmer.settings.security'
import { Route as FarmerSettingsProfileRouteImport } from './routes/farmer.settings.profile'
import { Route as FarmerSettingsPaymentsRouteImport } from './routes/farmer.settings.payments'
import { Route as FarmerSettingsNotificationsRouteImport } from './routes/farmer.settings.notifications'
import { Route as FarmerSettingsFarmRouteImport } from './routes/farmer.settings.farm'
import { Route as FarmerRevenueWithdrawalsRouteImport } from './routes/farmer.revenue.withdrawals'
import { Route as FarmerRevenueWithdrawRouteImport } from './routes/farmer.revenue.withdraw'
import { Route as FarmerRevenueTxIdRouteImport } from './routes/farmer.revenue.$txId'
import { Route as FarmerProductsNewRouteImport } from './routes/farmer.products.new'
import { Route as FarmerProductsImportRouteImport } from './routes/farmer.products.import'
import { Route as FarmerProductsProductIdRouteImport } from './routes/farmer.products.$productId'
import { Route as FarmerOrdersOrderIdRouteImport } from './routes/farmer.orders.$orderId'
import { Route as FarmerMessagesConversationIdRouteImport } from './routes/farmer.messages.$conversationId'
import { Route as DriverMissionsMissionIdRouteImport } from './routes/driver.missions.$missionId'
import { Route as DriverMessagesConversationIdRouteImport } from './routes/driver.messages.$conversationId'
import { Route as AdminValidationsValidationIdRouteImport } from './routes/admin.validations.$validationId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminDisputesDisputeIdRouteImport } from './routes/admin.disputes.$disputeId'
import { Route as RestaurantSuppliersSupplierIdEditRouteImport } from './routes/restaurant.suppliers.$supplierId.edit'
import { Route as FarmerStockMovementNewRouteImport } from './routes/farmer.stock.movement.new'
import { Route as FarmerStockProductIdHistoryRouteImport } from './routes/farmer.stock.$productId.history'
import { Route as FarmerProductsProductIdEditRouteImport } from './routes/farmer.products.$productId.edit'
import { Route as FarmerOrdersOrderIdReportRouteImport } from './routes/farmer.orders.$orderId.report'
import { Route as FarmerOrdersOrderIdRefuseRouteImport } from './routes/farmer.orders.$orderId.refuse'

const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRestaurantsRoute = ForRestaurantsRouteImport.update({
  id: '/for-restaurants',
  path: '/for-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFarmersRoute = ForFarmersRouteImport.update({
  id: '/for-farmers',
  path: '/for-farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForDriversRoute = ForDriversRouteImport.update({
  id: '/for-drivers',
  path: '/for-drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackPublicIdRoute = TrackPublicIdRouteImport.update({
  id: '/track/$publicId',
  path: '/track/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSettingsRoute = RestaurantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantRecurringRoute = RestaurantRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantNotificationsRoute = RestaurantNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantMessagesRoute = RestaurantMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantMarketplaceRoute = RestaurantMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantDashboardRoute = RestaurantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantCompareRoute = RestaurantCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantCheckoutRoute = RestaurantCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantCartRoute = RestaurantCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => RestaurantRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerSettingsRoute = FarmerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerNotificationsRoute = FarmerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerMessagesRoute = FarmerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAnalyticsRoute = FarmerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => FarmerRoute,
} as any)
const DriverVehicleRoute = DriverVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => DriverRoute,
} as any)
const DriverSettingsRoute = DriverSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverNotificationsRoute = DriverNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DriverRoute,
} as any)
const DriverMessagesRoute = DriverMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DriverRoute,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DriverRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const RestaurantSuppliersIndexRoute =
  RestaurantSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => RestaurantRoute,
  } as any)
const RestaurantSettingsIndexRoute = RestaurantSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RestaurantSettingsRoute,
} as any)
const RestaurantOrdersIndexRoute = RestaurantOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantMessagesIndexRoute = RestaurantMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RestaurantMessagesRoute,
} as any)
const RestaurantInvoicesIndexRoute = RestaurantInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => RestaurantRoute,
} as any)
const FarmerStockIndexRoute = FarmerStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerSettingsIndexRoute = FarmerSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerSettingsRoute,
} as any)
const FarmerRevenueIndexRoute = FarmerRevenueIndexRouteImport.update({
  id: '/revenue/',
  path: '/revenue/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProductsIndexRoute = FarmerProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOrdersIndexRoute = FarmerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerMessagesIndexRoute = FarmerMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerMessagesRoute,
} as any)
const DriverMissionsIndexRoute = DriverMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => DriverRoute,
} as any)
const DriverMessagesIndexRoute = DriverMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverMessagesRoute,
} as any)
const AdminValidationsIndexRoute = AdminValidationsIndexRouteImport.update({
  id: '/validations/',
  path: '/validations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesIndexRoute = AdminDisputesIndexRouteImport.update({
  id: '/disputes/',
  path: '/disputes/',
  getParentRoute: () => AdminRoute,
} as any)
const RestaurantSuppliersNewRoute = RestaurantSuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantSuppliersSupplierIdRoute =
  RestaurantSuppliersSupplierIdRouteImport.update({
    id: '/suppliers/$supplierId',
    path: '/suppliers/$supplierId',
    getParentRoute: () => RestaurantRoute,
  } as any)
const RestaurantSettingsTeamRoute = RestaurantSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => RestaurantSettingsRoute,
} as any)
const RestaurantSettingsSecurityRoute =
  RestaurantSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => RestaurantSettingsRoute,
  } as any)
const RestaurantSettingsProfileRoute =
  RestaurantSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => RestaurantSettingsRoute,
  } as any)
const RestaurantSettingsPaymentsRoute =
  RestaurantSettingsPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => RestaurantSettingsRoute,
  } as any)
const RestaurantSettingsNotificationsRoute =
  RestaurantSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => RestaurantSettingsRoute,
  } as any)
const RestaurantSettingsEstablishmentRoute =
  RestaurantSettingsEstablishmentRouteImport.update({
    id: '/establishment',
    path: '/establishment',
    getParentRoute: () => RestaurantSettingsRoute,
  } as any)
const RestaurantOrdersOrderIdRoute = RestaurantOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantMessagesConversationIdRoute =
  RestaurantMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => RestaurantMessagesRoute,
  } as any)
const RestaurantMarketplaceProductIdRoute =
  RestaurantMarketplaceProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => RestaurantMarketplaceRoute,
  } as any)
const RestaurantInvoicesInvoiceIdRoute =
  RestaurantInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => RestaurantRoute,
  } as any)
const FarmerStockInventoryRoute = FarmerStockInventoryRouteImport.update({
  id: '/stock/inventory',
  path: '/stock/inventory',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerSettingsTeamRoute = FarmerSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => FarmerSettingsRoute,
} as any)
const FarmerSettingsSecurityRoute = FarmerSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => FarmerSettingsRoute,
} as any)
const FarmerSettingsProfileRoute = FarmerSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FarmerSettingsRoute,
} as any)
const FarmerSettingsPaymentsRoute = FarmerSettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FarmerSettingsRoute,
} as any)
const FarmerSettingsNotificationsRoute =
  FarmerSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => FarmerSettingsRoute,
  } as any)
const FarmerSettingsFarmRoute = FarmerSettingsFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => FarmerSettingsRoute,
} as any)
const FarmerRevenueWithdrawalsRoute =
  FarmerRevenueWithdrawalsRouteImport.update({
    id: '/revenue/withdrawals',
    path: '/revenue/withdrawals',
    getParentRoute: () => FarmerRoute,
  } as any)
const FarmerRevenueWithdrawRoute = FarmerRevenueWithdrawRouteImport.update({
  id: '/revenue/withdraw',
  path: '/revenue/withdraw',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerRevenueTxIdRoute = FarmerRevenueTxIdRouteImport.update({
  id: '/revenue/$txId',
  path: '/revenue/$txId',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProductsNewRoute = FarmerProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProductsImportRoute = FarmerProductsImportRouteImport.update({
  id: '/products/import',
  path: '/products/import',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProductsProductIdRoute = FarmerProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOrdersOrderIdRoute = FarmerOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerMessagesConversationIdRoute =
  FarmerMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => FarmerMessagesRoute,
  } as any)
const DriverMissionsMissionIdRoute = DriverMissionsMissionIdRouteImport.update({
  id: '/missions/$missionId',
  path: '/missions/$missionId',
  getParentRoute: () => DriverRoute,
} as any)
const DriverMessagesConversationIdRoute =
  DriverMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => DriverMessagesRoute,
  } as any)
const AdminValidationsValidationIdRoute =
  AdminValidationsValidationIdRouteImport.update({
    id: '/validations/$validationId',
    path: '/validations/$validationId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesDisputeIdRoute = AdminDisputesDisputeIdRouteImport.update({
  id: '/disputes/$disputeId',
  path: '/disputes/$disputeId',
  getParentRoute: () => AdminRoute,
} as any)
const RestaurantSuppliersSupplierIdEditRoute =
  RestaurantSuppliersSupplierIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => RestaurantSuppliersSupplierIdRoute,
  } as any)
const FarmerStockMovementNewRoute = FarmerStockMovementNewRouteImport.update({
  id: '/stock/movement/new',
  path: '/stock/movement/new',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerStockProductIdHistoryRoute =
  FarmerStockProductIdHistoryRouteImport.update({
    id: '/stock/$productId/history',
    path: '/stock/$productId/history',
    getParentRoute: () => FarmerRoute,
  } as any)
const FarmerProductsProductIdEditRoute =
  FarmerProductsProductIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => FarmerProductsProductIdRoute,
  } as any)
const FarmerOrdersOrderIdReportRoute =
  FarmerOrdersOrderIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => FarmerOrdersOrderIdRoute,
  } as any)
const FarmerOrdersOrderIdRefuseRoute =
  FarmerOrdersOrderIdRefuseRouteImport.update({
    id: '/refuse',
    path: '/refuse',
    getParentRoute: () => FarmerOrdersOrderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/driver': typeof DriverRouteWithChildren
  '/faq': typeof FaqRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/for-drivers': typeof ForDriversRoute
  '/for-farmers': typeof ForFarmersRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/messages': typeof DriverMessagesRouteWithChildren
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/settings': typeof DriverSettingsRoute
  '/driver/vehicle': typeof DriverVehicleRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/messages': typeof FarmerMessagesRouteWithChildren
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/restaurant/cart': typeof RestaurantCartRoute
  '/restaurant/checkout': typeof RestaurantCheckoutRoute
  '/restaurant/compare': typeof RestaurantCompareRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/marketplace': typeof RestaurantMarketplaceRouteWithChildren
  '/restaurant/messages': typeof RestaurantMessagesRouteWithChildren
  '/restaurant/notifications': typeof RestaurantNotificationsRoute
  '/restaurant/recurring': typeof RestaurantRecurringRoute
  '/restaurant/settings': typeof RestaurantSettingsRouteWithChildren
  '/track/$publicId': typeof TrackPublicIdRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/validations/$validationId': typeof AdminValidationsValidationIdRoute
  '/driver/messages/$conversationId': typeof DriverMessagesConversationIdRoute
  '/driver/missions/$missionId': typeof DriverMissionsMissionIdRoute
  '/farmer/messages/$conversationId': typeof FarmerMessagesConversationIdRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRouteWithChildren
  '/farmer/products/$productId': typeof FarmerProductsProductIdRouteWithChildren
  '/farmer/products/import': typeof FarmerProductsImportRoute
  '/farmer/products/new': typeof FarmerProductsNewRoute
  '/farmer/revenue/$txId': typeof FarmerRevenueTxIdRoute
  '/farmer/revenue/withdraw': typeof FarmerRevenueWithdrawRoute
  '/farmer/revenue/withdrawals': typeof FarmerRevenueWithdrawalsRoute
  '/farmer/settings/farm': typeof FarmerSettingsFarmRoute
  '/farmer/settings/notifications': typeof FarmerSettingsNotificationsRoute
  '/farmer/settings/payments': typeof FarmerSettingsPaymentsRoute
  '/farmer/settings/profile': typeof FarmerSettingsProfileRoute
  '/farmer/settings/security': typeof FarmerSettingsSecurityRoute
  '/farmer/settings/team': typeof FarmerSettingsTeamRoute
  '/farmer/stock/inventory': typeof FarmerStockInventoryRoute
  '/restaurant/invoices/$invoiceId': typeof RestaurantInvoicesInvoiceIdRoute
  '/restaurant/marketplace/$productId': typeof RestaurantMarketplaceProductIdRoute
  '/restaurant/messages/$conversationId': typeof RestaurantMessagesConversationIdRoute
  '/restaurant/orders/$orderId': typeof RestaurantOrdersOrderIdRoute
  '/restaurant/settings/establishment': typeof RestaurantSettingsEstablishmentRoute
  '/restaurant/settings/notifications': typeof RestaurantSettingsNotificationsRoute
  '/restaurant/settings/payments': typeof RestaurantSettingsPaymentsRoute
  '/restaurant/settings/profile': typeof RestaurantSettingsProfileRoute
  '/restaurant/settings/security': typeof RestaurantSettingsSecurityRoute
  '/restaurant/settings/team': typeof RestaurantSettingsTeamRoute
  '/restaurant/suppliers/$supplierId': typeof RestaurantSuppliersSupplierIdRouteWithChildren
  '/restaurant/suppliers/new': typeof RestaurantSuppliersNewRoute
  '/admin/disputes/': typeof AdminDisputesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/validations/': typeof AdminValidationsIndexRoute
  '/driver/messages/': typeof DriverMessagesIndexRoute
  '/driver/missions/': typeof DriverMissionsIndexRoute
  '/farmer/messages/': typeof FarmerMessagesIndexRoute
  '/farmer/orders/': typeof FarmerOrdersIndexRoute
  '/farmer/products/': typeof FarmerProductsIndexRoute
  '/farmer/revenue/': typeof FarmerRevenueIndexRoute
  '/farmer/settings/': typeof FarmerSettingsIndexRoute
  '/farmer/stock/': typeof FarmerStockIndexRoute
  '/restaurant/invoices/': typeof RestaurantInvoicesIndexRoute
  '/restaurant/messages/': typeof RestaurantMessagesIndexRoute
  '/restaurant/orders/': typeof RestaurantOrdersIndexRoute
  '/restaurant/settings/': typeof RestaurantSettingsIndexRoute
  '/restaurant/suppliers/': typeof RestaurantSuppliersIndexRoute
  '/farmer/orders/$orderId/refuse': typeof FarmerOrdersOrderIdRefuseRoute
  '/farmer/orders/$orderId/report': typeof FarmerOrdersOrderIdReportRoute
  '/farmer/products/$productId/edit': typeof FarmerProductsProductIdEditRoute
  '/farmer/stock/$productId/history': typeof FarmerStockProductIdHistoryRoute
  '/farmer/stock/movement/new': typeof FarmerStockMovementNewRoute
  '/restaurant/suppliers/$supplierId/edit': typeof RestaurantSuppliersSupplierIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/driver': typeof DriverRouteWithChildren
  '/faq': typeof FaqRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/for-drivers': typeof ForDriversRoute
  '/for-farmers': typeof ForFarmersRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/settings': typeof DriverSettingsRoute
  '/driver/vehicle': typeof DriverVehicleRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/restaurant/cart': typeof RestaurantCartRoute
  '/restaurant/checkout': typeof RestaurantCheckoutRoute
  '/restaurant/compare': typeof RestaurantCompareRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/marketplace': typeof RestaurantMarketplaceRouteWithChildren
  '/restaurant/notifications': typeof RestaurantNotificationsRoute
  '/restaurant/recurring': typeof RestaurantRecurringRoute
  '/track/$publicId': typeof TrackPublicIdRoute
  '/blog': typeof BlogIndexRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/validations/$validationId': typeof AdminValidationsValidationIdRoute
  '/driver/messages/$conversationId': typeof DriverMessagesConversationIdRoute
  '/driver/missions/$missionId': typeof DriverMissionsMissionIdRoute
  '/farmer/messages/$conversationId': typeof FarmerMessagesConversationIdRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRouteWithChildren
  '/farmer/products/$productId': typeof FarmerProductsProductIdRouteWithChildren
  '/farmer/products/import': typeof FarmerProductsImportRoute
  '/farmer/products/new': typeof FarmerProductsNewRoute
  '/farmer/revenue/$txId': typeof FarmerRevenueTxIdRoute
  '/farmer/revenue/withdraw': typeof FarmerRevenueWithdrawRoute
  '/farmer/revenue/withdrawals': typeof FarmerRevenueWithdrawalsRoute
  '/farmer/settings/farm': typeof FarmerSettingsFarmRoute
  '/farmer/settings/notifications': typeof FarmerSettingsNotificationsRoute
  '/farmer/settings/payments': typeof FarmerSettingsPaymentsRoute
  '/farmer/settings/profile': typeof FarmerSettingsProfileRoute
  '/farmer/settings/security': typeof FarmerSettingsSecurityRoute
  '/farmer/settings/team': typeof FarmerSettingsTeamRoute
  '/farmer/stock/inventory': typeof FarmerStockInventoryRoute
  '/restaurant/invoices/$invoiceId': typeof RestaurantInvoicesInvoiceIdRoute
  '/restaurant/marketplace/$productId': typeof RestaurantMarketplaceProductIdRoute
  '/restaurant/messages/$conversationId': typeof RestaurantMessagesConversationIdRoute
  '/restaurant/orders/$orderId': typeof RestaurantOrdersOrderIdRoute
  '/restaurant/settings/establishment': typeof RestaurantSettingsEstablishmentRoute
  '/restaurant/settings/notifications': typeof RestaurantSettingsNotificationsRoute
  '/restaurant/settings/payments': typeof RestaurantSettingsPaymentsRoute
  '/restaurant/settings/profile': typeof RestaurantSettingsProfileRoute
  '/restaurant/settings/security': typeof RestaurantSettingsSecurityRoute
  '/restaurant/settings/team': typeof RestaurantSettingsTeamRoute
  '/restaurant/suppliers/$supplierId': typeof RestaurantSuppliersSupplierIdRouteWithChildren
  '/restaurant/suppliers/new': typeof RestaurantSuppliersNewRoute
  '/admin/disputes': typeof AdminDisputesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/validations': typeof AdminValidationsIndexRoute
  '/driver/messages': typeof DriverMessagesIndexRoute
  '/driver/missions': typeof DriverMissionsIndexRoute
  '/farmer/messages': typeof FarmerMessagesIndexRoute
  '/farmer/orders': typeof FarmerOrdersIndexRoute
  '/farmer/products': typeof FarmerProductsIndexRoute
  '/farmer/revenue': typeof FarmerRevenueIndexRoute
  '/farmer/settings': typeof FarmerSettingsIndexRoute
  '/farmer/stock': typeof FarmerStockIndexRoute
  '/restaurant/invoices': typeof RestaurantInvoicesIndexRoute
  '/restaurant/messages': typeof RestaurantMessagesIndexRoute
  '/restaurant/orders': typeof RestaurantOrdersIndexRoute
  '/restaurant/settings': typeof RestaurantSettingsIndexRoute
  '/restaurant/suppliers': typeof RestaurantSuppliersIndexRoute
  '/farmer/orders/$orderId/refuse': typeof FarmerOrdersOrderIdRefuseRoute
  '/farmer/orders/$orderId/report': typeof FarmerOrdersOrderIdReportRoute
  '/farmer/products/$productId/edit': typeof FarmerProductsProductIdEditRoute
  '/farmer/stock/$productId/history': typeof FarmerStockProductIdHistoryRoute
  '/farmer/stock/movement/new': typeof FarmerStockMovementNewRoute
  '/restaurant/suppliers/$supplierId/edit': typeof RestaurantSuppliersSupplierIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/driver': typeof DriverRouteWithChildren
  '/faq': typeof FaqRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/for-drivers': typeof ForDriversRoute
  '/for-farmers': typeof ForFarmersRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/messages': typeof DriverMessagesRouteWithChildren
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/settings': typeof DriverSettingsRoute
  '/driver/vehicle': typeof DriverVehicleRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/messages': typeof FarmerMessagesRouteWithChildren
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/restaurant/cart': typeof RestaurantCartRoute
  '/restaurant/checkout': typeof RestaurantCheckoutRoute
  '/restaurant/compare': typeof RestaurantCompareRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/marketplace': typeof RestaurantMarketplaceRouteWithChildren
  '/restaurant/messages': typeof RestaurantMessagesRouteWithChildren
  '/restaurant/notifications': typeof RestaurantNotificationsRoute
  '/restaurant/recurring': typeof RestaurantRecurringRoute
  '/restaurant/settings': typeof RestaurantSettingsRouteWithChildren
  '/track/$publicId': typeof TrackPublicIdRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/validations/$validationId': typeof AdminValidationsValidationIdRoute
  '/driver/messages/$conversationId': typeof DriverMessagesConversationIdRoute
  '/driver/missions/$missionId': typeof DriverMissionsMissionIdRoute
  '/farmer/messages/$conversationId': typeof FarmerMessagesConversationIdRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRouteWithChildren
  '/farmer/products/$productId': typeof FarmerProductsProductIdRouteWithChildren
  '/farmer/products/import': typeof FarmerProductsImportRoute
  '/farmer/products/new': typeof FarmerProductsNewRoute
  '/farmer/revenue/$txId': typeof FarmerRevenueTxIdRoute
  '/farmer/revenue/withdraw': typeof FarmerRevenueWithdrawRoute
  '/farmer/revenue/withdrawals': typeof FarmerRevenueWithdrawalsRoute
  '/farmer/settings/farm': typeof FarmerSettingsFarmRoute
  '/farmer/settings/notifications': typeof FarmerSettingsNotificationsRoute
  '/farmer/settings/payments': typeof FarmerSettingsPaymentsRoute
  '/farmer/settings/profile': typeof FarmerSettingsProfileRoute
  '/farmer/settings/security': typeof FarmerSettingsSecurityRoute
  '/farmer/settings/team': typeof FarmerSettingsTeamRoute
  '/farmer/stock/inventory': typeof FarmerStockInventoryRoute
  '/restaurant/invoices/$invoiceId': typeof RestaurantInvoicesInvoiceIdRoute
  '/restaurant/marketplace/$productId': typeof RestaurantMarketplaceProductIdRoute
  '/restaurant/messages/$conversationId': typeof RestaurantMessagesConversationIdRoute
  '/restaurant/orders/$orderId': typeof RestaurantOrdersOrderIdRoute
  '/restaurant/settings/establishment': typeof RestaurantSettingsEstablishmentRoute
  '/restaurant/settings/notifications': typeof RestaurantSettingsNotificationsRoute
  '/restaurant/settings/payments': typeof RestaurantSettingsPaymentsRoute
  '/restaurant/settings/profile': typeof RestaurantSettingsProfileRoute
  '/restaurant/settings/security': typeof RestaurantSettingsSecurityRoute
  '/restaurant/settings/team': typeof RestaurantSettingsTeamRoute
  '/restaurant/suppliers/$supplierId': typeof RestaurantSuppliersSupplierIdRouteWithChildren
  '/restaurant/suppliers/new': typeof RestaurantSuppliersNewRoute
  '/admin/disputes/': typeof AdminDisputesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/validations/': typeof AdminValidationsIndexRoute
  '/driver/messages/': typeof DriverMessagesIndexRoute
  '/driver/missions/': typeof DriverMissionsIndexRoute
  '/farmer/messages/': typeof FarmerMessagesIndexRoute
  '/farmer/orders/': typeof FarmerOrdersIndexRoute
  '/farmer/products/': typeof FarmerProductsIndexRoute
  '/farmer/revenue/': typeof FarmerRevenueIndexRoute
  '/farmer/settings/': typeof FarmerSettingsIndexRoute
  '/farmer/stock/': typeof FarmerStockIndexRoute
  '/restaurant/invoices/': typeof RestaurantInvoicesIndexRoute
  '/restaurant/messages/': typeof RestaurantMessagesIndexRoute
  '/restaurant/orders/': typeof RestaurantOrdersIndexRoute
  '/restaurant/settings/': typeof RestaurantSettingsIndexRoute
  '/restaurant/suppliers/': typeof RestaurantSuppliersIndexRoute
  '/farmer/orders/$orderId/refuse': typeof FarmerOrdersOrderIdRefuseRoute
  '/farmer/orders/$orderId/report': typeof FarmerOrdersOrderIdReportRoute
  '/farmer/products/$productId/edit': typeof FarmerProductsProductIdEditRoute
  '/farmer/stock/$productId/history': typeof FarmerStockProductIdHistoryRoute
  '/farmer/stock/movement/new': typeof FarmerStockMovementNewRoute
  '/restaurant/suppliers/$supplierId/edit': typeof RestaurantSuppliersSupplierIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/driver'
    | '/faq'
    | '/farmer'
    | '/for-drivers'
    | '/for-farmers'
    | '/for-restaurants'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/restaurant'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/settings'
    | '/blog/$slug'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/messages'
    | '/driver/notifications'
    | '/driver/settings'
    | '/driver/vehicle'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/messages'
    | '/farmer/notifications'
    | '/farmer/settings'
    | '/legal/privacy'
    | '/legal/terms'
    | '/restaurant/cart'
    | '/restaurant/checkout'
    | '/restaurant/compare'
    | '/restaurant/dashboard'
    | '/restaurant/marketplace'
    | '/restaurant/messages'
    | '/restaurant/notifications'
    | '/restaurant/recurring'
    | '/restaurant/settings'
    | '/track/$publicId'
    | '/blog/'
    | '/admin/disputes/$disputeId'
    | '/admin/users/$userId'
    | '/admin/validations/$validationId'
    | '/driver/messages/$conversationId'
    | '/driver/missions/$missionId'
    | '/farmer/messages/$conversationId'
    | '/farmer/orders/$orderId'
    | '/farmer/products/$productId'
    | '/farmer/products/import'
    | '/farmer/products/new'
    | '/farmer/revenue/$txId'
    | '/farmer/revenue/withdraw'
    | '/farmer/revenue/withdrawals'
    | '/farmer/settings/farm'
    | '/farmer/settings/notifications'
    | '/farmer/settings/payments'
    | '/farmer/settings/profile'
    | '/farmer/settings/security'
    | '/farmer/settings/team'
    | '/farmer/stock/inventory'
    | '/restaurant/invoices/$invoiceId'
    | '/restaurant/marketplace/$productId'
    | '/restaurant/messages/$conversationId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/settings/establishment'
    | '/restaurant/settings/notifications'
    | '/restaurant/settings/payments'
    | '/restaurant/settings/profile'
    | '/restaurant/settings/security'
    | '/restaurant/settings/team'
    | '/restaurant/suppliers/$supplierId'
    | '/restaurant/suppliers/new'
    | '/admin/disputes/'
    | '/admin/users/'
    | '/admin/validations/'
    | '/driver/messages/'
    | '/driver/missions/'
    | '/farmer/messages/'
    | '/farmer/orders/'
    | '/farmer/products/'
    | '/farmer/revenue/'
    | '/farmer/settings/'
    | '/farmer/stock/'
    | '/restaurant/invoices/'
    | '/restaurant/messages/'
    | '/restaurant/orders/'
    | '/restaurant/settings/'
    | '/restaurant/suppliers/'
    | '/farmer/orders/$orderId/refuse'
    | '/farmer/orders/$orderId/report'
    | '/farmer/products/$productId/edit'
    | '/farmer/stock/$productId/history'
    | '/farmer/stock/movement/new'
    | '/restaurant/suppliers/$supplierId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/driver'
    | '/faq'
    | '/farmer'
    | '/for-drivers'
    | '/for-farmers'
    | '/for-restaurants'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/restaurant'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/settings'
    | '/blog/$slug'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/notifications'
    | '/driver/settings'
    | '/driver/vehicle'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/notifications'
    | '/legal/privacy'
    | '/legal/terms'
    | '/restaurant/cart'
    | '/restaurant/checkout'
    | '/restaurant/compare'
    | '/restaurant/dashboard'
    | '/restaurant/marketplace'
    | '/restaurant/notifications'
    | '/restaurant/recurring'
    | '/track/$publicId'
    | '/blog'
    | '/admin/disputes/$disputeId'
    | '/admin/users/$userId'
    | '/admin/validations/$validationId'
    | '/driver/messages/$conversationId'
    | '/driver/missions/$missionId'
    | '/farmer/messages/$conversationId'
    | '/farmer/orders/$orderId'
    | '/farmer/products/$productId'
    | '/farmer/products/import'
    | '/farmer/products/new'
    | '/farmer/revenue/$txId'
    | '/farmer/revenue/withdraw'
    | '/farmer/revenue/withdrawals'
    | '/farmer/settings/farm'
    | '/farmer/settings/notifications'
    | '/farmer/settings/payments'
    | '/farmer/settings/profile'
    | '/farmer/settings/security'
    | '/farmer/settings/team'
    | '/farmer/stock/inventory'
    | '/restaurant/invoices/$invoiceId'
    | '/restaurant/marketplace/$productId'
    | '/restaurant/messages/$conversationId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/settings/establishment'
    | '/restaurant/settings/notifications'
    | '/restaurant/settings/payments'
    | '/restaurant/settings/profile'
    | '/restaurant/settings/security'
    | '/restaurant/settings/team'
    | '/restaurant/suppliers/$supplierId'
    | '/restaurant/suppliers/new'
    | '/admin/disputes'
    | '/admin/users'
    | '/admin/validations'
    | '/driver/messages'
    | '/driver/missions'
    | '/farmer/messages'
    | '/farmer/orders'
    | '/farmer/products'
    | '/farmer/revenue'
    | '/farmer/settings'
    | '/farmer/stock'
    | '/restaurant/invoices'
    | '/restaurant/messages'
    | '/restaurant/orders'
    | '/restaurant/settings'
    | '/restaurant/suppliers'
    | '/farmer/orders/$orderId/refuse'
    | '/farmer/orders/$orderId/report'
    | '/farmer/products/$productId/edit'
    | '/farmer/stock/$productId/history'
    | '/farmer/stock/movement/new'
    | '/restaurant/suppliers/$supplierId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/driver'
    | '/faq'
    | '/farmer'
    | '/for-drivers'
    | '/for-farmers'
    | '/for-restaurants'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/restaurant'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/settings'
    | '/blog/$slug'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/messages'
    | '/driver/notifications'
    | '/driver/settings'
    | '/driver/vehicle'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/messages'
    | '/farmer/notifications'
    | '/farmer/settings'
    | '/legal/privacy'
    | '/legal/terms'
    | '/restaurant/cart'
    | '/restaurant/checkout'
    | '/restaurant/compare'
    | '/restaurant/dashboard'
    | '/restaurant/marketplace'
    | '/restaurant/messages'
    | '/restaurant/notifications'
    | '/restaurant/recurring'
    | '/restaurant/settings'
    | '/track/$publicId'
    | '/blog/'
    | '/admin/disputes/$disputeId'
    | '/admin/users/$userId'
    | '/admin/validations/$validationId'
    | '/driver/messages/$conversationId'
    | '/driver/missions/$missionId'
    | '/farmer/messages/$conversationId'
    | '/farmer/orders/$orderId'
    | '/farmer/products/$productId'
    | '/farmer/products/import'
    | '/farmer/products/new'
    | '/farmer/revenue/$txId'
    | '/farmer/revenue/withdraw'
    | '/farmer/revenue/withdrawals'
    | '/farmer/settings/farm'
    | '/farmer/settings/notifications'
    | '/farmer/settings/payments'
    | '/farmer/settings/profile'
    | '/farmer/settings/security'
    | '/farmer/settings/team'
    | '/farmer/stock/inventory'
    | '/restaurant/invoices/$invoiceId'
    | '/restaurant/marketplace/$productId'
    | '/restaurant/messages/$conversationId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/settings/establishment'
    | '/restaurant/settings/notifications'
    | '/restaurant/settings/payments'
    | '/restaurant/settings/profile'
    | '/restaurant/settings/security'
    | '/restaurant/settings/team'
    | '/restaurant/suppliers/$supplierId'
    | '/restaurant/suppliers/new'
    | '/admin/disputes/'
    | '/admin/users/'
    | '/admin/validations/'
    | '/driver/messages/'
    | '/driver/missions/'
    | '/farmer/messages/'
    | '/farmer/orders/'
    | '/farmer/products/'
    | '/farmer/revenue/'
    | '/farmer/settings/'
    | '/farmer/stock/'
    | '/restaurant/invoices/'
    | '/restaurant/messages/'
    | '/restaurant/orders/'
    | '/restaurant/settings/'
    | '/restaurant/suppliers/'
    | '/farmer/orders/$orderId/refuse'
    | '/farmer/orders/$orderId/report'
    | '/farmer/products/$productId/edit'
    | '/farmer/stock/$productId/history'
    | '/farmer/stock/movement/new'
    | '/restaurant/suppliers/$supplierId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DriverRoute: typeof DriverRouteWithChildren
  FaqRoute: typeof FaqRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  ForDriversRoute: typeof ForDriversRoute
  ForFarmersRoute: typeof ForFarmersRoute
  ForRestaurantsRoute: typeof ForRestaurantsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantRoute: typeof RestaurantRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  TrackPublicIdRoute: typeof TrackPublicIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-restaurants': {
      id: '/for-restaurants'
      path: '/for-restaurants'
      fullPath: '/for-restaurants'
      preLoaderRoute: typeof ForRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-farmers': {
      id: '/for-farmers'
      path: '/for-farmers'
      fullPath: '/for-farmers'
      preLoaderRoute: typeof ForFarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-drivers': {
      id: '/for-drivers'
      path: '/for-drivers'
      fullPath: '/for-drivers'
      preLoaderRoute: typeof ForDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$publicId': {
      id: '/track/$publicId'
      path: '/track/$publicId'
      fullPath: '/track/$publicId'
      preLoaderRoute: typeof TrackPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/settings': {
      id: '/restaurant/settings'
      path: '/settings'
      fullPath: '/restaurant/settings'
      preLoaderRoute: typeof RestaurantSettingsRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/recurring': {
      id: '/restaurant/recurring'
      path: '/recurring'
      fullPath: '/restaurant/recurring'
      preLoaderRoute: typeof RestaurantRecurringRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/notifications': {
      id: '/restaurant/notifications'
      path: '/notifications'
      fullPath: '/restaurant/notifications'
      preLoaderRoute: typeof RestaurantNotificationsRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/messages': {
      id: '/restaurant/messages'
      path: '/messages'
      fullPath: '/restaurant/messages'
      preLoaderRoute: typeof RestaurantMessagesRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/marketplace': {
      id: '/restaurant/marketplace'
      path: '/marketplace'
      fullPath: '/restaurant/marketplace'
      preLoaderRoute: typeof RestaurantMarketplaceRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/dashboard': {
      id: '/restaurant/dashboard'
      path: '/dashboard'
      fullPath: '/restaurant/dashboard'
      preLoaderRoute: typeof RestaurantDashboardRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/compare': {
      id: '/restaurant/compare'
      path: '/compare'
      fullPath: '/restaurant/compare'
      preLoaderRoute: typeof RestaurantCompareRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/checkout': {
      id: '/restaurant/checkout'
      path: '/checkout'
      fullPath: '/restaurant/checkout'
      preLoaderRoute: typeof RestaurantCheckoutRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/cart': {
      id: '/restaurant/cart'
      path: '/cart'
      fullPath: '/restaurant/cart'
      preLoaderRoute: typeof RestaurantCartRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/settings': {
      id: '/farmer/settings'
      path: '/settings'
      fullPath: '/farmer/settings'
      preLoaderRoute: typeof FarmerSettingsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/notifications': {
      id: '/farmer/notifications'
      path: '/notifications'
      fullPath: '/farmer/notifications'
      preLoaderRoute: typeof FarmerNotificationsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/messages': {
      id: '/farmer/messages'
      path: '/messages'
      fullPath: '/farmer/messages'
      preLoaderRoute: typeof FarmerMessagesRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/dashboard': {
      id: '/farmer/dashboard'
      path: '/dashboard'
      fullPath: '/farmer/dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/analytics': {
      id: '/farmer/analytics'
      path: '/analytics'
      fullPath: '/farmer/analytics'
      preLoaderRoute: typeof FarmerAnalyticsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/driver/vehicle': {
      id: '/driver/vehicle'
      path: '/vehicle'
      fullPath: '/driver/vehicle'
      preLoaderRoute: typeof DriverVehicleRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/settings': {
      id: '/driver/settings'
      path: '/settings'
      fullPath: '/driver/settings'
      preLoaderRoute: typeof DriverSettingsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/notifications': {
      id: '/driver/notifications'
      path: '/notifications'
      fullPath: '/driver/notifications'
      preLoaderRoute: typeof DriverNotificationsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/messages': {
      id: '/driver/messages'
      path: '/messages'
      fullPath: '/driver/messages'
      preLoaderRoute: typeof DriverMessagesRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof DriverRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/restaurant/suppliers/': {
      id: '/restaurant/suppliers/'
      path: '/suppliers'
      fullPath: '/restaurant/suppliers/'
      preLoaderRoute: typeof RestaurantSuppliersIndexRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/settings/': {
      id: '/restaurant/settings/'
      path: '/'
      fullPath: '/restaurant/settings/'
      preLoaderRoute: typeof RestaurantSettingsIndexRouteImport
      parentRoute: typeof RestaurantSettingsRoute
    }
    '/restaurant/orders/': {
      id: '/restaurant/orders/'
      path: '/orders'
      fullPath: '/restaurant/orders/'
      preLoaderRoute: typeof RestaurantOrdersIndexRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/messages/': {
      id: '/restaurant/messages/'
      path: '/'
      fullPath: '/restaurant/messages/'
      preLoaderRoute: typeof RestaurantMessagesIndexRouteImport
      parentRoute: typeof RestaurantMessagesRoute
    }
    '/restaurant/invoices/': {
      id: '/restaurant/invoices/'
      path: '/invoices'
      fullPath: '/restaurant/invoices/'
      preLoaderRoute: typeof RestaurantInvoicesIndexRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/farmer/stock/': {
      id: '/farmer/stock/'
      path: '/stock'
      fullPath: '/farmer/stock/'
      preLoaderRoute: typeof FarmerStockIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/settings/': {
      id: '/farmer/settings/'
      path: '/'
      fullPath: '/farmer/settings/'
      preLoaderRoute: typeof FarmerSettingsIndexRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/revenue/': {
      id: '/farmer/revenue/'
      path: '/revenue'
      fullPath: '/farmer/revenue/'
      preLoaderRoute: typeof FarmerRevenueIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/products/': {
      id: '/farmer/products/'
      path: '/products'
      fullPath: '/farmer/products/'
      preLoaderRoute: typeof FarmerProductsIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/orders/': {
      id: '/farmer/orders/'
      path: '/orders'
      fullPath: '/farmer/orders/'
      preLoaderRoute: typeof FarmerOrdersIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/messages/': {
      id: '/farmer/messages/'
      path: '/'
      fullPath: '/farmer/messages/'
      preLoaderRoute: typeof FarmerMessagesIndexRouteImport
      parentRoute: typeof FarmerMessagesRoute
    }
    '/driver/missions/': {
      id: '/driver/missions/'
      path: '/missions'
      fullPath: '/driver/missions/'
      preLoaderRoute: typeof DriverMissionsIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/messages/': {
      id: '/driver/messages/'
      path: '/'
      fullPath: '/driver/messages/'
      preLoaderRoute: typeof DriverMessagesIndexRouteImport
      parentRoute: typeof DriverMessagesRoute
    }
    '/admin/validations/': {
      id: '/admin/validations/'
      path: '/validations'
      fullPath: '/admin/validations/'
      preLoaderRoute: typeof AdminValidationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes/': {
      id: '/admin/disputes/'
      path: '/disputes'
      fullPath: '/admin/disputes/'
      preLoaderRoute: typeof AdminDisputesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/restaurant/suppliers/new': {
      id: '/restaurant/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/restaurant/suppliers/new'
      preLoaderRoute: typeof RestaurantSuppliersNewRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/suppliers/$supplierId': {
      id: '/restaurant/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/restaurant/suppliers/$supplierId'
      preLoaderRoute: typeof RestaurantSuppliersSupplierIdRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/settings/team': {
      id: '/restaurant/settings/team'
      path: '/team'
      fullPath: '/restaurant/settings/team'
      preLoaderRoute: typeof RestaurantSettingsTeamRouteImport
      parentRoute: typeof RestaurantSettingsRoute
    }
    '/restaurant/settings/security': {
      id: '/restaurant/settings/security'
      path: '/security'
      fullPath: '/restaurant/settings/security'
      preLoaderRoute: typeof RestaurantSettingsSecurityRouteImport
      parentRoute: typeof RestaurantSettingsRoute
    }
    '/restaurant/settings/profile': {
      id: '/restaurant/settings/profile'
      path: '/profile'
      fullPath: '/restaurant/settings/profile'
      preLoaderRoute: typeof RestaurantSettingsProfileRouteImport
      parentRoute: typeof RestaurantSettingsRoute
    }
    '/restaurant/settings/payments': {
      id: '/restaurant/settings/payments'
      path: '/payments'
      fullPath: '/restaurant/settings/payments'
      preLoaderRoute: typeof RestaurantSettingsPaymentsRouteImport
      parentRoute: typeof RestaurantSettingsRoute
    }
    '/restaurant/settings/notifications': {
      id: '/restaurant/settings/notifications'
      path: '/notifications'
      fullPath: '/restaurant/settings/notifications'
      preLoaderRoute: typeof RestaurantSettingsNotificationsRouteImport
      parentRoute: typeof RestaurantSettingsRoute
    }
    '/restaurant/settings/establishment': {
      id: '/restaurant/settings/establishment'
      path: '/establishment'
      fullPath: '/restaurant/settings/establishment'
      preLoaderRoute: typeof RestaurantSettingsEstablishmentRouteImport
      parentRoute: typeof RestaurantSettingsRoute
    }
    '/restaurant/orders/$orderId': {
      id: '/restaurant/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/restaurant/orders/$orderId'
      preLoaderRoute: typeof RestaurantOrdersOrderIdRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/messages/$conversationId': {
      id: '/restaurant/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/restaurant/messages/$conversationId'
      preLoaderRoute: typeof RestaurantMessagesConversationIdRouteImport
      parentRoute: typeof RestaurantMessagesRoute
    }
    '/restaurant/marketplace/$productId': {
      id: '/restaurant/marketplace/$productId'
      path: '/$productId'
      fullPath: '/restaurant/marketplace/$productId'
      preLoaderRoute: typeof RestaurantMarketplaceProductIdRouteImport
      parentRoute: typeof RestaurantMarketplaceRoute
    }
    '/restaurant/invoices/$invoiceId': {
      id: '/restaurant/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/restaurant/invoices/$invoiceId'
      preLoaderRoute: typeof RestaurantInvoicesInvoiceIdRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/farmer/stock/inventory': {
      id: '/farmer/stock/inventory'
      path: '/stock/inventory'
      fullPath: '/farmer/stock/inventory'
      preLoaderRoute: typeof FarmerStockInventoryRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/settings/team': {
      id: '/farmer/settings/team'
      path: '/team'
      fullPath: '/farmer/settings/team'
      preLoaderRoute: typeof FarmerSettingsTeamRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/settings/security': {
      id: '/farmer/settings/security'
      path: '/security'
      fullPath: '/farmer/settings/security'
      preLoaderRoute: typeof FarmerSettingsSecurityRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/settings/profile': {
      id: '/farmer/settings/profile'
      path: '/profile'
      fullPath: '/farmer/settings/profile'
      preLoaderRoute: typeof FarmerSettingsProfileRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/settings/payments': {
      id: '/farmer/settings/payments'
      path: '/payments'
      fullPath: '/farmer/settings/payments'
      preLoaderRoute: typeof FarmerSettingsPaymentsRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/settings/notifications': {
      id: '/farmer/settings/notifications'
      path: '/notifications'
      fullPath: '/farmer/settings/notifications'
      preLoaderRoute: typeof FarmerSettingsNotificationsRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/settings/farm': {
      id: '/farmer/settings/farm'
      path: '/farm'
      fullPath: '/farmer/settings/farm'
      preLoaderRoute: typeof FarmerSettingsFarmRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/revenue/withdrawals': {
      id: '/farmer/revenue/withdrawals'
      path: '/revenue/withdrawals'
      fullPath: '/farmer/revenue/withdrawals'
      preLoaderRoute: typeof FarmerRevenueWithdrawalsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/revenue/withdraw': {
      id: '/farmer/revenue/withdraw'
      path: '/revenue/withdraw'
      fullPath: '/farmer/revenue/withdraw'
      preLoaderRoute: typeof FarmerRevenueWithdrawRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/revenue/$txId': {
      id: '/farmer/revenue/$txId'
      path: '/revenue/$txId'
      fullPath: '/farmer/revenue/$txId'
      preLoaderRoute: typeof FarmerRevenueTxIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/products/new': {
      id: '/farmer/products/new'
      path: '/products/new'
      fullPath: '/farmer/products/new'
      preLoaderRoute: typeof FarmerProductsNewRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/products/import': {
      id: '/farmer/products/import'
      path: '/products/import'
      fullPath: '/farmer/products/import'
      preLoaderRoute: typeof FarmerProductsImportRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/products/$productId': {
      id: '/farmer/products/$productId'
      path: '/products/$productId'
      fullPath: '/farmer/products/$productId'
      preLoaderRoute: typeof FarmerProductsProductIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/orders/$orderId': {
      id: '/farmer/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/farmer/orders/$orderId'
      preLoaderRoute: typeof FarmerOrdersOrderIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/messages/$conversationId': {
      id: '/farmer/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/farmer/messages/$conversationId'
      preLoaderRoute: typeof FarmerMessagesConversationIdRouteImport
      parentRoute: typeof FarmerMessagesRoute
    }
    '/driver/missions/$missionId': {
      id: '/driver/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/driver/missions/$missionId'
      preLoaderRoute: typeof DriverMissionsMissionIdRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/messages/$conversationId': {
      id: '/driver/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/driver/messages/$conversationId'
      preLoaderRoute: typeof DriverMessagesConversationIdRouteImport
      parentRoute: typeof DriverMessagesRoute
    }
    '/admin/validations/$validationId': {
      id: '/admin/validations/$validationId'
      path: '/validations/$validationId'
      fullPath: '/admin/validations/$validationId'
      preLoaderRoute: typeof AdminValidationsValidationIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes/$disputeId': {
      id: '/admin/disputes/$disputeId'
      path: '/disputes/$disputeId'
      fullPath: '/admin/disputes/$disputeId'
      preLoaderRoute: typeof AdminDisputesDisputeIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/restaurant/suppliers/$supplierId/edit': {
      id: '/restaurant/suppliers/$supplierId/edit'
      path: '/edit'
      fullPath: '/restaurant/suppliers/$supplierId/edit'
      preLoaderRoute: typeof RestaurantSuppliersSupplierIdEditRouteImport
      parentRoute: typeof RestaurantSuppliersSupplierIdRoute
    }
    '/farmer/stock/movement/new': {
      id: '/farmer/stock/movement/new'
      path: '/stock/movement/new'
      fullPath: '/farmer/stock/movement/new'
      preLoaderRoute: typeof FarmerStockMovementNewRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/stock/$productId/history': {
      id: '/farmer/stock/$productId/history'
      path: '/stock/$productId/history'
      fullPath: '/farmer/stock/$productId/history'
      preLoaderRoute: typeof FarmerStockProductIdHistoryRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/products/$productId/edit': {
      id: '/farmer/products/$productId/edit'
      path: '/edit'
      fullPath: '/farmer/products/$productId/edit'
      preLoaderRoute: typeof FarmerProductsProductIdEditRouteImport
      parentRoute: typeof FarmerProductsProductIdRoute
    }
    '/farmer/orders/$orderId/report': {
      id: '/farmer/orders/$orderId/report'
      path: '/report'
      fullPath: '/farmer/orders/$orderId/report'
      preLoaderRoute: typeof FarmerOrdersOrderIdReportRouteImport
      parentRoute: typeof FarmerOrdersOrderIdRoute
    }
    '/farmer/orders/$orderId/refuse': {
      id: '/farmer/orders/$orderId/refuse'
      path: '/refuse'
      fullPath: '/farmer/orders/$orderId/refuse'
      preLoaderRoute: typeof FarmerOrdersOrderIdRefuseRouteImport
      parentRoute: typeof FarmerOrdersOrderIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminDisputesDisputeIdRoute: typeof AdminDisputesDisputeIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminValidationsValidationIdRoute: typeof AdminValidationsValidationIdRoute
  AdminDisputesIndexRoute: typeof AdminDisputesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminValidationsIndexRoute: typeof AdminValidationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminDisputesDisputeIdRoute: AdminDisputesDisputeIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminValidationsValidationIdRoute: AdminValidationsValidationIdRoute,
  AdminDisputesIndexRoute: AdminDisputesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminValidationsIndexRoute: AdminValidationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DriverMessagesRouteChildren {
  DriverMessagesConversationIdRoute: typeof DriverMessagesConversationIdRoute
  DriverMessagesIndexRoute: typeof DriverMessagesIndexRoute
}

const DriverMessagesRouteChildren: DriverMessagesRouteChildren = {
  DriverMessagesConversationIdRoute: DriverMessagesConversationIdRoute,
  DriverMessagesIndexRoute: DriverMessagesIndexRoute,
}

const DriverMessagesRouteWithChildren = DriverMessagesRoute._addFileChildren(
  DriverMessagesRouteChildren,
)

interface DriverRouteChildren {
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHistoryRoute: typeof DriverHistoryRoute
  DriverMessagesRoute: typeof DriverMessagesRouteWithChildren
  DriverNotificationsRoute: typeof DriverNotificationsRoute
  DriverSettingsRoute: typeof DriverSettingsRoute
  DriverVehicleRoute: typeof DriverVehicleRoute
  DriverMissionsMissionIdRoute: typeof DriverMissionsMissionIdRoute
  DriverMissionsIndexRoute: typeof DriverMissionsIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverDashboardRoute: DriverDashboardRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHistoryRoute: DriverHistoryRoute,
  DriverMessagesRoute: DriverMessagesRouteWithChildren,
  DriverNotificationsRoute: DriverNotificationsRoute,
  DriverSettingsRoute: DriverSettingsRoute,
  DriverVehicleRoute: DriverVehicleRoute,
  DriverMissionsMissionIdRoute: DriverMissionsMissionIdRoute,
  DriverMissionsIndexRoute: DriverMissionsIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface FarmerMessagesRouteChildren {
  FarmerMessagesConversationIdRoute: typeof FarmerMessagesConversationIdRoute
  FarmerMessagesIndexRoute: typeof FarmerMessagesIndexRoute
}

const FarmerMessagesRouteChildren: FarmerMessagesRouteChildren = {
  FarmerMessagesConversationIdRoute: FarmerMessagesConversationIdRoute,
  FarmerMessagesIndexRoute: FarmerMessagesIndexRoute,
}

const FarmerMessagesRouteWithChildren = FarmerMessagesRoute._addFileChildren(
  FarmerMessagesRouteChildren,
)

interface FarmerSettingsRouteChildren {
  FarmerSettingsFarmRoute: typeof FarmerSettingsFarmRoute
  FarmerSettingsNotificationsRoute: typeof FarmerSettingsNotificationsRoute
  FarmerSettingsPaymentsRoute: typeof FarmerSettingsPaymentsRoute
  FarmerSettingsProfileRoute: typeof FarmerSettingsProfileRoute
  FarmerSettingsSecurityRoute: typeof FarmerSettingsSecurityRoute
  FarmerSettingsTeamRoute: typeof FarmerSettingsTeamRoute
  FarmerSettingsIndexRoute: typeof FarmerSettingsIndexRoute
}

const FarmerSettingsRouteChildren: FarmerSettingsRouteChildren = {
  FarmerSettingsFarmRoute: FarmerSettingsFarmRoute,
  FarmerSettingsNotificationsRoute: FarmerSettingsNotificationsRoute,
  FarmerSettingsPaymentsRoute: FarmerSettingsPaymentsRoute,
  FarmerSettingsProfileRoute: FarmerSettingsProfileRoute,
  FarmerSettingsSecurityRoute: FarmerSettingsSecurityRoute,
  FarmerSettingsTeamRoute: FarmerSettingsTeamRoute,
  FarmerSettingsIndexRoute: FarmerSettingsIndexRoute,
}

const FarmerSettingsRouteWithChildren = FarmerSettingsRoute._addFileChildren(
  FarmerSettingsRouteChildren,
)

interface FarmerOrdersOrderIdRouteChildren {
  FarmerOrdersOrderIdRefuseRoute: typeof FarmerOrdersOrderIdRefuseRoute
  FarmerOrdersOrderIdReportRoute: typeof FarmerOrdersOrderIdReportRoute
}

const FarmerOrdersOrderIdRouteChildren: FarmerOrdersOrderIdRouteChildren = {
  FarmerOrdersOrderIdRefuseRoute: FarmerOrdersOrderIdRefuseRoute,
  FarmerOrdersOrderIdReportRoute: FarmerOrdersOrderIdReportRoute,
}

const FarmerOrdersOrderIdRouteWithChildren =
  FarmerOrdersOrderIdRoute._addFileChildren(FarmerOrdersOrderIdRouteChildren)

interface FarmerProductsProductIdRouteChildren {
  FarmerProductsProductIdEditRoute: typeof FarmerProductsProductIdEditRoute
}

const FarmerProductsProductIdRouteChildren: FarmerProductsProductIdRouteChildren =
  {
    FarmerProductsProductIdEditRoute: FarmerProductsProductIdEditRoute,
  }

const FarmerProductsProductIdRouteWithChildren =
  FarmerProductsProductIdRoute._addFileChildren(
    FarmerProductsProductIdRouteChildren,
  )

interface FarmerRouteChildren {
  FarmerAnalyticsRoute: typeof FarmerAnalyticsRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  FarmerMessagesRoute: typeof FarmerMessagesRouteWithChildren
  FarmerNotificationsRoute: typeof FarmerNotificationsRoute
  FarmerSettingsRoute: typeof FarmerSettingsRouteWithChildren
  FarmerOrdersOrderIdRoute: typeof FarmerOrdersOrderIdRouteWithChildren
  FarmerProductsProductIdRoute: typeof FarmerProductsProductIdRouteWithChildren
  FarmerProductsImportRoute: typeof FarmerProductsImportRoute
  FarmerProductsNewRoute: typeof FarmerProductsNewRoute
  FarmerRevenueTxIdRoute: typeof FarmerRevenueTxIdRoute
  FarmerRevenueWithdrawRoute: typeof FarmerRevenueWithdrawRoute
  FarmerRevenueWithdrawalsRoute: typeof FarmerRevenueWithdrawalsRoute
  FarmerStockInventoryRoute: typeof FarmerStockInventoryRoute
  FarmerOrdersIndexRoute: typeof FarmerOrdersIndexRoute
  FarmerProductsIndexRoute: typeof FarmerProductsIndexRoute
  FarmerRevenueIndexRoute: typeof FarmerRevenueIndexRoute
  FarmerStockIndexRoute: typeof FarmerStockIndexRoute
  FarmerStockProductIdHistoryRoute: typeof FarmerStockProductIdHistoryRoute
  FarmerStockMovementNewRoute: typeof FarmerStockMovementNewRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerAnalyticsRoute: FarmerAnalyticsRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  FarmerMessagesRoute: FarmerMessagesRouteWithChildren,
  FarmerNotificationsRoute: FarmerNotificationsRoute,
  FarmerSettingsRoute: FarmerSettingsRouteWithChildren,
  FarmerOrdersOrderIdRoute: FarmerOrdersOrderIdRouteWithChildren,
  FarmerProductsProductIdRoute: FarmerProductsProductIdRouteWithChildren,
  FarmerProductsImportRoute: FarmerProductsImportRoute,
  FarmerProductsNewRoute: FarmerProductsNewRoute,
  FarmerRevenueTxIdRoute: FarmerRevenueTxIdRoute,
  FarmerRevenueWithdrawRoute: FarmerRevenueWithdrawRoute,
  FarmerRevenueWithdrawalsRoute: FarmerRevenueWithdrawalsRoute,
  FarmerStockInventoryRoute: FarmerStockInventoryRoute,
  FarmerOrdersIndexRoute: FarmerOrdersIndexRoute,
  FarmerProductsIndexRoute: FarmerProductsIndexRoute,
  FarmerRevenueIndexRoute: FarmerRevenueIndexRoute,
  FarmerStockIndexRoute: FarmerStockIndexRoute,
  FarmerStockProductIdHistoryRoute: FarmerStockProductIdHistoryRoute,
  FarmerStockMovementNewRoute: FarmerStockMovementNewRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface RestaurantMarketplaceRouteChildren {
  RestaurantMarketplaceProductIdRoute: typeof RestaurantMarketplaceProductIdRoute
}

const RestaurantMarketplaceRouteChildren: RestaurantMarketplaceRouteChildren = {
  RestaurantMarketplaceProductIdRoute: RestaurantMarketplaceProductIdRoute,
}

const RestaurantMarketplaceRouteWithChildren =
  RestaurantMarketplaceRoute._addFileChildren(
    RestaurantMarketplaceRouteChildren,
  )

interface RestaurantMessagesRouteChildren {
  RestaurantMessagesConversationIdRoute: typeof RestaurantMessagesConversationIdRoute
  RestaurantMessagesIndexRoute: typeof RestaurantMessagesIndexRoute
}

const RestaurantMessagesRouteChildren: RestaurantMessagesRouteChildren = {
  RestaurantMessagesConversationIdRoute: RestaurantMessagesConversationIdRoute,
  RestaurantMessagesIndexRoute: RestaurantMessagesIndexRoute,
}

const RestaurantMessagesRouteWithChildren =
  RestaurantMessagesRoute._addFileChildren(RestaurantMessagesRouteChildren)

interface RestaurantSettingsRouteChildren {
  RestaurantSettingsEstablishmentRoute: typeof RestaurantSettingsEstablishmentRoute
  RestaurantSettingsNotificationsRoute: typeof RestaurantSettingsNotificationsRoute
  RestaurantSettingsPaymentsRoute: typeof RestaurantSettingsPaymentsRoute
  RestaurantSettingsProfileRoute: typeof RestaurantSettingsProfileRoute
  RestaurantSettingsSecurityRoute: typeof RestaurantSettingsSecurityRoute
  RestaurantSettingsTeamRoute: typeof RestaurantSettingsTeamRoute
  RestaurantSettingsIndexRoute: typeof RestaurantSettingsIndexRoute
}

const RestaurantSettingsRouteChildren: RestaurantSettingsRouteChildren = {
  RestaurantSettingsEstablishmentRoute: RestaurantSettingsEstablishmentRoute,
  RestaurantSettingsNotificationsRoute: RestaurantSettingsNotificationsRoute,
  RestaurantSettingsPaymentsRoute: RestaurantSettingsPaymentsRoute,
  RestaurantSettingsProfileRoute: RestaurantSettingsProfileRoute,
  RestaurantSettingsSecurityRoute: RestaurantSettingsSecurityRoute,
  RestaurantSettingsTeamRoute: RestaurantSettingsTeamRoute,
  RestaurantSettingsIndexRoute: RestaurantSettingsIndexRoute,
}

const RestaurantSettingsRouteWithChildren =
  RestaurantSettingsRoute._addFileChildren(RestaurantSettingsRouteChildren)

interface RestaurantSuppliersSupplierIdRouteChildren {
  RestaurantSuppliersSupplierIdEditRoute: typeof RestaurantSuppliersSupplierIdEditRoute
}

const RestaurantSuppliersSupplierIdRouteChildren: RestaurantSuppliersSupplierIdRouteChildren =
  {
    RestaurantSuppliersSupplierIdEditRoute:
      RestaurantSuppliersSupplierIdEditRoute,
  }

const RestaurantSuppliersSupplierIdRouteWithChildren =
  RestaurantSuppliersSupplierIdRoute._addFileChildren(
    RestaurantSuppliersSupplierIdRouteChildren,
  )

interface RestaurantRouteChildren {
  RestaurantCartRoute: typeof RestaurantCartRoute
  RestaurantCheckoutRoute: typeof RestaurantCheckoutRoute
  RestaurantCompareRoute: typeof RestaurantCompareRoute
  RestaurantDashboardRoute: typeof RestaurantDashboardRoute
  RestaurantMarketplaceRoute: typeof RestaurantMarketplaceRouteWithChildren
  RestaurantMessagesRoute: typeof RestaurantMessagesRouteWithChildren
  RestaurantNotificationsRoute: typeof RestaurantNotificationsRoute
  RestaurantRecurringRoute: typeof RestaurantRecurringRoute
  RestaurantSettingsRoute: typeof RestaurantSettingsRouteWithChildren
  RestaurantInvoicesInvoiceIdRoute: typeof RestaurantInvoicesInvoiceIdRoute
  RestaurantOrdersOrderIdRoute: typeof RestaurantOrdersOrderIdRoute
  RestaurantSuppliersSupplierIdRoute: typeof RestaurantSuppliersSupplierIdRouteWithChildren
  RestaurantSuppliersNewRoute: typeof RestaurantSuppliersNewRoute
  RestaurantInvoicesIndexRoute: typeof RestaurantInvoicesIndexRoute
  RestaurantOrdersIndexRoute: typeof RestaurantOrdersIndexRoute
  RestaurantSuppliersIndexRoute: typeof RestaurantSuppliersIndexRoute
}

const RestaurantRouteChildren: RestaurantRouteChildren = {
  RestaurantCartRoute: RestaurantCartRoute,
  RestaurantCheckoutRoute: RestaurantCheckoutRoute,
  RestaurantCompareRoute: RestaurantCompareRoute,
  RestaurantDashboardRoute: RestaurantDashboardRoute,
  RestaurantMarketplaceRoute: RestaurantMarketplaceRouteWithChildren,
  RestaurantMessagesRoute: RestaurantMessagesRouteWithChildren,
  RestaurantNotificationsRoute: RestaurantNotificationsRoute,
  RestaurantRecurringRoute: RestaurantRecurringRoute,
  RestaurantSettingsRoute: RestaurantSettingsRouteWithChildren,
  RestaurantInvoicesInvoiceIdRoute: RestaurantInvoicesInvoiceIdRoute,
  RestaurantOrdersOrderIdRoute: RestaurantOrdersOrderIdRoute,
  RestaurantSuppliersSupplierIdRoute:
    RestaurantSuppliersSupplierIdRouteWithChildren,
  RestaurantSuppliersNewRoute: RestaurantSuppliersNewRoute,
  RestaurantInvoicesIndexRoute: RestaurantInvoicesIndexRoute,
  RestaurantOrdersIndexRoute: RestaurantOrdersIndexRoute,
  RestaurantSuppliersIndexRoute: RestaurantSuppliersIndexRoute,
}

const RestaurantRouteWithChildren = RestaurantRoute._addFileChildren(
  RestaurantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DriverRoute: DriverRouteWithChildren,
  FaqRoute: FaqRoute,
  FarmerRoute: FarmerRouteWithChildren,
  ForDriversRoute: ForDriversRoute,
  ForFarmersRoute: ForFarmersRoute,
  ForRestaurantsRoute: ForRestaurantsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantRoute: RestaurantRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  TrackPublicIdRoute: TrackPublicIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
