/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackPublicIdRouteImport } from './routes/track.$publicId'
import { Route as RestaurantSuppliersRouteImport } from './routes/restaurant.suppliers'
import { Route as RestaurantSettingsRouteImport } from './routes/restaurant.settings'
import { Route as RestaurantRecurringRouteImport } from './routes/restaurant.recurring'
import { Route as RestaurantOrdersRouteImport } from './routes/restaurant.orders'
import { Route as RestaurantNotificationsRouteImport } from './routes/restaurant.notifications'
import { Route as RestaurantMessagesRouteImport } from './routes/restaurant.messages'
import { Route as RestaurantMarketplaceRouteImport } from './routes/restaurant.marketplace'
import { Route as RestaurantInvoicesRouteImport } from './routes/restaurant.invoices'
import { Route as RestaurantDashboardRouteImport } from './routes/restaurant.dashboard'
import { Route as RestaurantCheckoutRouteImport } from './routes/restaurant.checkout'
import { Route as RestaurantCartRouteImport } from './routes/restaurant.cart'
import { Route as FarmerStockRouteImport } from './routes/farmer.stock'
import { Route as FarmerSettingsRouteImport } from './routes/farmer.settings'
import { Route as FarmerRevenueRouteImport } from './routes/farmer.revenue'
import { Route as FarmerProductsRouteImport } from './routes/farmer.products'
import { Route as FarmerOrdersRouteImport } from './routes/farmer.orders'
import { Route as FarmerNotificationsRouteImport } from './routes/farmer.notifications'
import { Route as FarmerMessagesRouteImport } from './routes/farmer.messages'
import { Route as FarmerDashboardRouteImport } from './routes/farmer.dashboard'
import { Route as FarmerAnalyticsRouteImport } from './routes/farmer.analytics'
import { Route as DriverVehicleRouteImport } from './routes/driver.vehicle'
import { Route as DriverNotificationsRouteImport } from './routes/driver.notifications'
import { Route as DriverMissionsRouteImport } from './routes/driver.missions'
import { Route as DriverMessagesRouteImport } from './routes/driver.messages'
import { Route as DriverHistoryRouteImport } from './routes/driver.history'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as DriverDashboardRouteImport } from './routes/driver.dashboard'
import { Route as RestaurantSuppliersNewRouteImport } from './routes/restaurant.suppliers.new'
import { Route as RestaurantSuppliersSupplierIdRouteImport } from './routes/restaurant.suppliers.$supplierId'
import { Route as RestaurantOrdersOrderIdRouteImport } from './routes/restaurant.orders.$orderId'
import { Route as RestaurantMarketplaceProductIdRouteImport } from './routes/restaurant.marketplace.$productId'
import { Route as RestaurantInvoicesInvoiceIdRouteImport } from './routes/restaurant.invoices.$invoiceId'
import { Route as FarmerStockInventoryRouteImport } from './routes/farmer.stock.inventory'
import { Route as FarmerRevenueWithdrawalsRouteImport } from './routes/farmer.revenue.withdrawals'
import { Route as FarmerRevenueWithdrawRouteImport } from './routes/farmer.revenue.withdraw'
import { Route as FarmerRevenueTxIdRouteImport } from './routes/farmer.revenue.$txId'
import { Route as FarmerProductsNewRouteImport } from './routes/farmer.products.new'
import { Route as FarmerProductsImportRouteImport } from './routes/farmer.products.import'
import { Route as FarmerProductsProductIdRouteImport } from './routes/farmer.products.$productId'
import { Route as FarmerOrdersOrderIdRouteImport } from './routes/farmer.orders.$orderId'
import { Route as DriverMissionsMissionIdRouteImport } from './routes/driver.missions.$missionId'
import { Route as RestaurantSuppliersSupplierIdEditRouteImport } from './routes/restaurant.suppliers.$supplierId.edit'
import { Route as FarmerStockMovementNewRouteImport } from './routes/farmer.stock.movement.new'
import { Route as FarmerStockProductIdHistoryRouteImport } from './routes/farmer.stock.$productId.history'
import { Route as FarmerProductsProductIdEditRouteImport } from './routes/farmer.products.$productId.edit'
import { Route as FarmerOrdersOrderIdReportRouteImport } from './routes/farmer.orders.$orderId.report'
import { Route as FarmerOrdersOrderIdRefuseRouteImport } from './routes/farmer.orders.$orderId.refuse'

const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackPublicIdRoute = TrackPublicIdRouteImport.update({
  id: '/track/$publicId',
  path: '/track/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSuppliersRoute = RestaurantSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantSettingsRoute = RestaurantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantRecurringRoute = RestaurantRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantOrdersRoute = RestaurantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantNotificationsRoute = RestaurantNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantMessagesRoute = RestaurantMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantMarketplaceRoute = RestaurantMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantInvoicesRoute = RestaurantInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantDashboardRoute = RestaurantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantCheckoutRoute = RestaurantCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantCartRoute = RestaurantCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => RestaurantRoute,
} as any)
const FarmerStockRoute = FarmerStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerSettingsRoute = FarmerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerRevenueRoute = FarmerRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProductsRoute = FarmerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOrdersRoute = FarmerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerNotificationsRoute = FarmerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerMessagesRoute = FarmerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAnalyticsRoute = FarmerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => FarmerRoute,
} as any)
const DriverVehicleRoute = DriverVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => DriverRoute,
} as any)
const DriverNotificationsRoute = DriverNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DriverRoute,
} as any)
const DriverMissionsRoute = DriverMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => DriverRoute,
} as any)
const DriverMessagesRoute = DriverMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DriverRoute,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DriverRoute,
} as any)
const RestaurantSuppliersNewRoute = RestaurantSuppliersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RestaurantSuppliersRoute,
} as any)
const RestaurantSuppliersSupplierIdRoute =
  RestaurantSuppliersSupplierIdRouteImport.update({
    id: '/$supplierId',
    path: '/$supplierId',
    getParentRoute: () => RestaurantSuppliersRoute,
  } as any)
const RestaurantOrdersOrderIdRoute = RestaurantOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => RestaurantOrdersRoute,
} as any)
const RestaurantMarketplaceProductIdRoute =
  RestaurantMarketplaceProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => RestaurantMarketplaceRoute,
  } as any)
const RestaurantInvoicesInvoiceIdRoute =
  RestaurantInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => RestaurantInvoicesRoute,
  } as any)
const FarmerStockInventoryRoute = FarmerStockInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => FarmerStockRoute,
} as any)
const FarmerRevenueWithdrawalsRoute =
  FarmerRevenueWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => FarmerRevenueRoute,
  } as any)
const FarmerRevenueWithdrawRoute = FarmerRevenueWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => FarmerRevenueRoute,
} as any)
const FarmerRevenueTxIdRoute = FarmerRevenueTxIdRouteImport.update({
  id: '/$txId',
  path: '/$txId',
  getParentRoute: () => FarmerRevenueRoute,
} as any)
const FarmerProductsNewRoute = FarmerProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FarmerProductsRoute,
} as any)
const FarmerProductsImportRoute = FarmerProductsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => FarmerProductsRoute,
} as any)
const FarmerProductsProductIdRoute = FarmerProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => FarmerProductsRoute,
} as any)
const FarmerOrdersOrderIdRoute = FarmerOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => FarmerOrdersRoute,
} as any)
const DriverMissionsMissionIdRoute = DriverMissionsMissionIdRouteImport.update({
  id: '/$missionId',
  path: '/$missionId',
  getParentRoute: () => DriverMissionsRoute,
} as any)
const RestaurantSuppliersSupplierIdEditRoute =
  RestaurantSuppliersSupplierIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => RestaurantSuppliersSupplierIdRoute,
  } as any)
const FarmerStockMovementNewRoute = FarmerStockMovementNewRouteImport.update({
  id: '/movement/new',
  path: '/movement/new',
  getParentRoute: () => FarmerStockRoute,
} as any)
const FarmerStockProductIdHistoryRoute =
  FarmerStockProductIdHistoryRouteImport.update({
    id: '/$productId/history',
    path: '/$productId/history',
    getParentRoute: () => FarmerStockRoute,
  } as any)
const FarmerProductsProductIdEditRoute =
  FarmerProductsProductIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => FarmerProductsProductIdRoute,
  } as any)
const FarmerOrdersOrderIdReportRoute =
  FarmerOrdersOrderIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => FarmerOrdersOrderIdRoute,
  } as any)
const FarmerOrdersOrderIdRefuseRoute =
  FarmerOrdersOrderIdRefuseRouteImport.update({
    id: '/refuse',
    path: '/refuse',
    getParentRoute: () => FarmerOrdersOrderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRouteWithChildren
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/messages': typeof DriverMessagesRoute
  '/driver/missions': typeof DriverMissionsRouteWithChildren
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/vehicle': typeof DriverVehicleRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/messages': typeof FarmerMessagesRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/orders': typeof FarmerOrdersRouteWithChildren
  '/farmer/products': typeof FarmerProductsRouteWithChildren
  '/farmer/revenue': typeof FarmerRevenueRouteWithChildren
  '/farmer/settings': typeof FarmerSettingsRoute
  '/farmer/stock': typeof FarmerStockRouteWithChildren
  '/restaurant/cart': typeof RestaurantCartRoute
  '/restaurant/checkout': typeof RestaurantCheckoutRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/invoices': typeof RestaurantInvoicesRouteWithChildren
  '/restaurant/marketplace': typeof RestaurantMarketplaceRouteWithChildren
  '/restaurant/messages': typeof RestaurantMessagesRoute
  '/restaurant/notifications': typeof RestaurantNotificationsRoute
  '/restaurant/orders': typeof RestaurantOrdersRouteWithChildren
  '/restaurant/recurring': typeof RestaurantRecurringRoute
  '/restaurant/settings': typeof RestaurantSettingsRoute
  '/restaurant/suppliers': typeof RestaurantSuppliersRouteWithChildren
  '/track/$publicId': typeof TrackPublicIdRoute
  '/driver/missions/$missionId': typeof DriverMissionsMissionIdRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRouteWithChildren
  '/farmer/products/$productId': typeof FarmerProductsProductIdRouteWithChildren
  '/farmer/products/import': typeof FarmerProductsImportRoute
  '/farmer/products/new': typeof FarmerProductsNewRoute
  '/farmer/revenue/$txId': typeof FarmerRevenueTxIdRoute
  '/farmer/revenue/withdraw': typeof FarmerRevenueWithdrawRoute
  '/farmer/revenue/withdrawals': typeof FarmerRevenueWithdrawalsRoute
  '/farmer/stock/inventory': typeof FarmerStockInventoryRoute
  '/restaurant/invoices/$invoiceId': typeof RestaurantInvoicesInvoiceIdRoute
  '/restaurant/marketplace/$productId': typeof RestaurantMarketplaceProductIdRoute
  '/restaurant/orders/$orderId': typeof RestaurantOrdersOrderIdRoute
  '/restaurant/suppliers/$supplierId': typeof RestaurantSuppliersSupplierIdRouteWithChildren
  '/restaurant/suppliers/new': typeof RestaurantSuppliersNewRoute
  '/farmer/orders/$orderId/refuse': typeof FarmerOrdersOrderIdRefuseRoute
  '/farmer/orders/$orderId/report': typeof FarmerOrdersOrderIdReportRoute
  '/farmer/products/$productId/edit': typeof FarmerProductsProductIdEditRoute
  '/farmer/stock/$productId/history': typeof FarmerStockProductIdHistoryRoute
  '/farmer/stock/movement/new': typeof FarmerStockMovementNewRoute
  '/restaurant/suppliers/$supplierId/edit': typeof RestaurantSuppliersSupplierIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRouteWithChildren
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/messages': typeof DriverMessagesRoute
  '/driver/missions': typeof DriverMissionsRouteWithChildren
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/vehicle': typeof DriverVehicleRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/messages': typeof FarmerMessagesRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/orders': typeof FarmerOrdersRouteWithChildren
  '/farmer/products': typeof FarmerProductsRouteWithChildren
  '/farmer/revenue': typeof FarmerRevenueRouteWithChildren
  '/farmer/settings': typeof FarmerSettingsRoute
  '/farmer/stock': typeof FarmerStockRouteWithChildren
  '/restaurant/cart': typeof RestaurantCartRoute
  '/restaurant/checkout': typeof RestaurantCheckoutRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/invoices': typeof RestaurantInvoicesRouteWithChildren
  '/restaurant/marketplace': typeof RestaurantMarketplaceRouteWithChildren
  '/restaurant/messages': typeof RestaurantMessagesRoute
  '/restaurant/notifications': typeof RestaurantNotificationsRoute
  '/restaurant/orders': typeof RestaurantOrdersRouteWithChildren
  '/restaurant/recurring': typeof RestaurantRecurringRoute
  '/restaurant/settings': typeof RestaurantSettingsRoute
  '/restaurant/suppliers': typeof RestaurantSuppliersRouteWithChildren
  '/track/$publicId': typeof TrackPublicIdRoute
  '/driver/missions/$missionId': typeof DriverMissionsMissionIdRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRouteWithChildren
  '/farmer/products/$productId': typeof FarmerProductsProductIdRouteWithChildren
  '/farmer/products/import': typeof FarmerProductsImportRoute
  '/farmer/products/new': typeof FarmerProductsNewRoute
  '/farmer/revenue/$txId': typeof FarmerRevenueTxIdRoute
  '/farmer/revenue/withdraw': typeof FarmerRevenueWithdrawRoute
  '/farmer/revenue/withdrawals': typeof FarmerRevenueWithdrawalsRoute
  '/farmer/stock/inventory': typeof FarmerStockInventoryRoute
  '/restaurant/invoices/$invoiceId': typeof RestaurantInvoicesInvoiceIdRoute
  '/restaurant/marketplace/$productId': typeof RestaurantMarketplaceProductIdRoute
  '/restaurant/orders/$orderId': typeof RestaurantOrdersOrderIdRoute
  '/restaurant/suppliers/$supplierId': typeof RestaurantSuppliersSupplierIdRouteWithChildren
  '/restaurant/suppliers/new': typeof RestaurantSuppliersNewRoute
  '/farmer/orders/$orderId/refuse': typeof FarmerOrdersOrderIdRefuseRoute
  '/farmer/orders/$orderId/report': typeof FarmerOrdersOrderIdReportRoute
  '/farmer/products/$productId/edit': typeof FarmerProductsProductIdEditRoute
  '/farmer/stock/$productId/history': typeof FarmerStockProductIdHistoryRoute
  '/farmer/stock/movement/new': typeof FarmerStockMovementNewRoute
  '/restaurant/suppliers/$supplierId/edit': typeof RestaurantSuppliersSupplierIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRouteWithChildren
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/messages': typeof DriverMessagesRoute
  '/driver/missions': typeof DriverMissionsRouteWithChildren
  '/driver/notifications': typeof DriverNotificationsRoute
  '/driver/vehicle': typeof DriverVehicleRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/messages': typeof FarmerMessagesRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/orders': typeof FarmerOrdersRouteWithChildren
  '/farmer/products': typeof FarmerProductsRouteWithChildren
  '/farmer/revenue': typeof FarmerRevenueRouteWithChildren
  '/farmer/settings': typeof FarmerSettingsRoute
  '/farmer/stock': typeof FarmerStockRouteWithChildren
  '/restaurant/cart': typeof RestaurantCartRoute
  '/restaurant/checkout': typeof RestaurantCheckoutRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/invoices': typeof RestaurantInvoicesRouteWithChildren
  '/restaurant/marketplace': typeof RestaurantMarketplaceRouteWithChildren
  '/restaurant/messages': typeof RestaurantMessagesRoute
  '/restaurant/notifications': typeof RestaurantNotificationsRoute
  '/restaurant/orders': typeof RestaurantOrdersRouteWithChildren
  '/restaurant/recurring': typeof RestaurantRecurringRoute
  '/restaurant/settings': typeof RestaurantSettingsRoute
  '/restaurant/suppliers': typeof RestaurantSuppliersRouteWithChildren
  '/track/$publicId': typeof TrackPublicIdRoute
  '/driver/missions/$missionId': typeof DriverMissionsMissionIdRoute
  '/farmer/orders/$orderId': typeof FarmerOrdersOrderIdRouteWithChildren
  '/farmer/products/$productId': typeof FarmerProductsProductIdRouteWithChildren
  '/farmer/products/import': typeof FarmerProductsImportRoute
  '/farmer/products/new': typeof FarmerProductsNewRoute
  '/farmer/revenue/$txId': typeof FarmerRevenueTxIdRoute
  '/farmer/revenue/withdraw': typeof FarmerRevenueWithdrawRoute
  '/farmer/revenue/withdrawals': typeof FarmerRevenueWithdrawalsRoute
  '/farmer/stock/inventory': typeof FarmerStockInventoryRoute
  '/restaurant/invoices/$invoiceId': typeof RestaurantInvoicesInvoiceIdRoute
  '/restaurant/marketplace/$productId': typeof RestaurantMarketplaceProductIdRoute
  '/restaurant/orders/$orderId': typeof RestaurantOrdersOrderIdRoute
  '/restaurant/suppliers/$supplierId': typeof RestaurantSuppliersSupplierIdRouteWithChildren
  '/restaurant/suppliers/new': typeof RestaurantSuppliersNewRoute
  '/farmer/orders/$orderId/refuse': typeof FarmerOrdersOrderIdRefuseRoute
  '/farmer/orders/$orderId/report': typeof FarmerOrdersOrderIdReportRoute
  '/farmer/products/$productId/edit': typeof FarmerProductsProductIdEditRoute
  '/farmer/stock/$productId/history': typeof FarmerStockProductIdHistoryRoute
  '/farmer/stock/movement/new': typeof FarmerStockMovementNewRoute
  '/restaurant/suppliers/$supplierId/edit': typeof RestaurantSuppliersSupplierIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/driver'
    | '/farmer'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/restaurant'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/messages'
    | '/driver/missions'
    | '/driver/notifications'
    | '/driver/vehicle'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/messages'
    | '/farmer/notifications'
    | '/farmer/orders'
    | '/farmer/products'
    | '/farmer/revenue'
    | '/farmer/settings'
    | '/farmer/stock'
    | '/restaurant/cart'
    | '/restaurant/checkout'
    | '/restaurant/dashboard'
    | '/restaurant/invoices'
    | '/restaurant/marketplace'
    | '/restaurant/messages'
    | '/restaurant/notifications'
    | '/restaurant/orders'
    | '/restaurant/recurring'
    | '/restaurant/settings'
    | '/restaurant/suppliers'
    | '/track/$publicId'
    | '/driver/missions/$missionId'
    | '/farmer/orders/$orderId'
    | '/farmer/products/$productId'
    | '/farmer/products/import'
    | '/farmer/products/new'
    | '/farmer/revenue/$txId'
    | '/farmer/revenue/withdraw'
    | '/farmer/revenue/withdrawals'
    | '/farmer/stock/inventory'
    | '/restaurant/invoices/$invoiceId'
    | '/restaurant/marketplace/$productId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/suppliers/$supplierId'
    | '/restaurant/suppliers/new'
    | '/farmer/orders/$orderId/refuse'
    | '/farmer/orders/$orderId/report'
    | '/farmer/products/$productId/edit'
    | '/farmer/stock/$productId/history'
    | '/farmer/stock/movement/new'
    | '/restaurant/suppliers/$supplierId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/driver'
    | '/farmer'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/restaurant'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/messages'
    | '/driver/missions'
    | '/driver/notifications'
    | '/driver/vehicle'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/messages'
    | '/farmer/notifications'
    | '/farmer/orders'
    | '/farmer/products'
    | '/farmer/revenue'
    | '/farmer/settings'
    | '/farmer/stock'
    | '/restaurant/cart'
    | '/restaurant/checkout'
    | '/restaurant/dashboard'
    | '/restaurant/invoices'
    | '/restaurant/marketplace'
    | '/restaurant/messages'
    | '/restaurant/notifications'
    | '/restaurant/orders'
    | '/restaurant/recurring'
    | '/restaurant/settings'
    | '/restaurant/suppliers'
    | '/track/$publicId'
    | '/driver/missions/$missionId'
    | '/farmer/orders/$orderId'
    | '/farmer/products/$productId'
    | '/farmer/products/import'
    | '/farmer/products/new'
    | '/farmer/revenue/$txId'
    | '/farmer/revenue/withdraw'
    | '/farmer/revenue/withdrawals'
    | '/farmer/stock/inventory'
    | '/restaurant/invoices/$invoiceId'
    | '/restaurant/marketplace/$productId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/suppliers/$supplierId'
    | '/restaurant/suppliers/new'
    | '/farmer/orders/$orderId/refuse'
    | '/farmer/orders/$orderId/report'
    | '/farmer/products/$productId/edit'
    | '/farmer/stock/$productId/history'
    | '/farmer/stock/movement/new'
    | '/restaurant/suppliers/$supplierId/edit'
  id:
    | '__root__'
    | '/'
    | '/driver'
    | '/farmer'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/restaurant'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/messages'
    | '/driver/missions'
    | '/driver/notifications'
    | '/driver/vehicle'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/messages'
    | '/farmer/notifications'
    | '/farmer/orders'
    | '/farmer/products'
    | '/farmer/revenue'
    | '/farmer/settings'
    | '/farmer/stock'
    | '/restaurant/cart'
    | '/restaurant/checkout'
    | '/restaurant/dashboard'
    | '/restaurant/invoices'
    | '/restaurant/marketplace'
    | '/restaurant/messages'
    | '/restaurant/notifications'
    | '/restaurant/orders'
    | '/restaurant/recurring'
    | '/restaurant/settings'
    | '/restaurant/suppliers'
    | '/track/$publicId'
    | '/driver/missions/$missionId'
    | '/farmer/orders/$orderId'
    | '/farmer/products/$productId'
    | '/farmer/products/import'
    | '/farmer/products/new'
    | '/farmer/revenue/$txId'
    | '/farmer/revenue/withdraw'
    | '/farmer/revenue/withdrawals'
    | '/farmer/stock/inventory'
    | '/restaurant/invoices/$invoiceId'
    | '/restaurant/marketplace/$productId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/suppliers/$supplierId'
    | '/restaurant/suppliers/new'
    | '/farmer/orders/$orderId/refuse'
    | '/farmer/orders/$orderId/report'
    | '/farmer/products/$productId/edit'
    | '/farmer/stock/$productId/history'
    | '/farmer/stock/movement/new'
    | '/restaurant/suppliers/$supplierId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriverRoute: typeof DriverRouteWithChildren
  FarmerRoute: typeof FarmerRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantRoute: typeof RestaurantRouteWithChildren
  TrackPublicIdRoute: typeof TrackPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$publicId': {
      id: '/track/$publicId'
      path: '/track/$publicId'
      fullPath: '/track/$publicId'
      preLoaderRoute: typeof TrackPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/suppliers': {
      id: '/restaurant/suppliers'
      path: '/suppliers'
      fullPath: '/restaurant/suppliers'
      preLoaderRoute: typeof RestaurantSuppliersRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/settings': {
      id: '/restaurant/settings'
      path: '/settings'
      fullPath: '/restaurant/settings'
      preLoaderRoute: typeof RestaurantSettingsRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/recurring': {
      id: '/restaurant/recurring'
      path: '/recurring'
      fullPath: '/restaurant/recurring'
      preLoaderRoute: typeof RestaurantRecurringRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/orders': {
      id: '/restaurant/orders'
      path: '/orders'
      fullPath: '/restaurant/orders'
      preLoaderRoute: typeof RestaurantOrdersRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/notifications': {
      id: '/restaurant/notifications'
      path: '/notifications'
      fullPath: '/restaurant/notifications'
      preLoaderRoute: typeof RestaurantNotificationsRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/messages': {
      id: '/restaurant/messages'
      path: '/messages'
      fullPath: '/restaurant/messages'
      preLoaderRoute: typeof RestaurantMessagesRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/marketplace': {
      id: '/restaurant/marketplace'
      path: '/marketplace'
      fullPath: '/restaurant/marketplace'
      preLoaderRoute: typeof RestaurantMarketplaceRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/invoices': {
      id: '/restaurant/invoices'
      path: '/invoices'
      fullPath: '/restaurant/invoices'
      preLoaderRoute: typeof RestaurantInvoicesRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/dashboard': {
      id: '/restaurant/dashboard'
      path: '/dashboard'
      fullPath: '/restaurant/dashboard'
      preLoaderRoute: typeof RestaurantDashboardRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/checkout': {
      id: '/restaurant/checkout'
      path: '/checkout'
      fullPath: '/restaurant/checkout'
      preLoaderRoute: typeof RestaurantCheckoutRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/restaurant/cart': {
      id: '/restaurant/cart'
      path: '/cart'
      fullPath: '/restaurant/cart'
      preLoaderRoute: typeof RestaurantCartRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/farmer/stock': {
      id: '/farmer/stock'
      path: '/stock'
      fullPath: '/farmer/stock'
      preLoaderRoute: typeof FarmerStockRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/settings': {
      id: '/farmer/settings'
      path: '/settings'
      fullPath: '/farmer/settings'
      preLoaderRoute: typeof FarmerSettingsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/revenue': {
      id: '/farmer/revenue'
      path: '/revenue'
      fullPath: '/farmer/revenue'
      preLoaderRoute: typeof FarmerRevenueRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/products': {
      id: '/farmer/products'
      path: '/products'
      fullPath: '/farmer/products'
      preLoaderRoute: typeof FarmerProductsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/orders': {
      id: '/farmer/orders'
      path: '/orders'
      fullPath: '/farmer/orders'
      preLoaderRoute: typeof FarmerOrdersRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/notifications': {
      id: '/farmer/notifications'
      path: '/notifications'
      fullPath: '/farmer/notifications'
      preLoaderRoute: typeof FarmerNotificationsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/messages': {
      id: '/farmer/messages'
      path: '/messages'
      fullPath: '/farmer/messages'
      preLoaderRoute: typeof FarmerMessagesRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/dashboard': {
      id: '/farmer/dashboard'
      path: '/dashboard'
      fullPath: '/farmer/dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/analytics': {
      id: '/farmer/analytics'
      path: '/analytics'
      fullPath: '/farmer/analytics'
      preLoaderRoute: typeof FarmerAnalyticsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/driver/vehicle': {
      id: '/driver/vehicle'
      path: '/vehicle'
      fullPath: '/driver/vehicle'
      preLoaderRoute: typeof DriverVehicleRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/notifications': {
      id: '/driver/notifications'
      path: '/notifications'
      fullPath: '/driver/notifications'
      preLoaderRoute: typeof DriverNotificationsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/missions': {
      id: '/driver/missions'
      path: '/missions'
      fullPath: '/driver/missions'
      preLoaderRoute: typeof DriverMissionsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/messages': {
      id: '/driver/messages'
      path: '/messages'
      fullPath: '/driver/messages'
      preLoaderRoute: typeof DriverMessagesRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof DriverRoute
    }
    '/restaurant/suppliers/new': {
      id: '/restaurant/suppliers/new'
      path: '/new'
      fullPath: '/restaurant/suppliers/new'
      preLoaderRoute: typeof RestaurantSuppliersNewRouteImport
      parentRoute: typeof RestaurantSuppliersRoute
    }
    '/restaurant/suppliers/$supplierId': {
      id: '/restaurant/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/restaurant/suppliers/$supplierId'
      preLoaderRoute: typeof RestaurantSuppliersSupplierIdRouteImport
      parentRoute: typeof RestaurantSuppliersRoute
    }
    '/restaurant/orders/$orderId': {
      id: '/restaurant/orders/$orderId'
      path: '/$orderId'
      fullPath: '/restaurant/orders/$orderId'
      preLoaderRoute: typeof RestaurantOrdersOrderIdRouteImport
      parentRoute: typeof RestaurantOrdersRoute
    }
    '/restaurant/marketplace/$productId': {
      id: '/restaurant/marketplace/$productId'
      path: '/$productId'
      fullPath: '/restaurant/marketplace/$productId'
      preLoaderRoute: typeof RestaurantMarketplaceProductIdRouteImport
      parentRoute: typeof RestaurantMarketplaceRoute
    }
    '/restaurant/invoices/$invoiceId': {
      id: '/restaurant/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/restaurant/invoices/$invoiceId'
      preLoaderRoute: typeof RestaurantInvoicesInvoiceIdRouteImport
      parentRoute: typeof RestaurantInvoicesRoute
    }
    '/farmer/stock/inventory': {
      id: '/farmer/stock/inventory'
      path: '/inventory'
      fullPath: '/farmer/stock/inventory'
      preLoaderRoute: typeof FarmerStockInventoryRouteImport
      parentRoute: typeof FarmerStockRoute
    }
    '/farmer/revenue/withdrawals': {
      id: '/farmer/revenue/withdrawals'
      path: '/withdrawals'
      fullPath: '/farmer/revenue/withdrawals'
      preLoaderRoute: typeof FarmerRevenueWithdrawalsRouteImport
      parentRoute: typeof FarmerRevenueRoute
    }
    '/farmer/revenue/withdraw': {
      id: '/farmer/revenue/withdraw'
      path: '/withdraw'
      fullPath: '/farmer/revenue/withdraw'
      preLoaderRoute: typeof FarmerRevenueWithdrawRouteImport
      parentRoute: typeof FarmerRevenueRoute
    }
    '/farmer/revenue/$txId': {
      id: '/farmer/revenue/$txId'
      path: '/$txId'
      fullPath: '/farmer/revenue/$txId'
      preLoaderRoute: typeof FarmerRevenueTxIdRouteImport
      parentRoute: typeof FarmerRevenueRoute
    }
    '/farmer/products/new': {
      id: '/farmer/products/new'
      path: '/new'
      fullPath: '/farmer/products/new'
      preLoaderRoute: typeof FarmerProductsNewRouteImport
      parentRoute: typeof FarmerProductsRoute
    }
    '/farmer/products/import': {
      id: '/farmer/products/import'
      path: '/import'
      fullPath: '/farmer/products/import'
      preLoaderRoute: typeof FarmerProductsImportRouteImport
      parentRoute: typeof FarmerProductsRoute
    }
    '/farmer/products/$productId': {
      id: '/farmer/products/$productId'
      path: '/$productId'
      fullPath: '/farmer/products/$productId'
      preLoaderRoute: typeof FarmerProductsProductIdRouteImport
      parentRoute: typeof FarmerProductsRoute
    }
    '/farmer/orders/$orderId': {
      id: '/farmer/orders/$orderId'
      path: '/$orderId'
      fullPath: '/farmer/orders/$orderId'
      preLoaderRoute: typeof FarmerOrdersOrderIdRouteImport
      parentRoute: typeof FarmerOrdersRoute
    }
    '/driver/missions/$missionId': {
      id: '/driver/missions/$missionId'
      path: '/$missionId'
      fullPath: '/driver/missions/$missionId'
      preLoaderRoute: typeof DriverMissionsMissionIdRouteImport
      parentRoute: typeof DriverMissionsRoute
    }
    '/restaurant/suppliers/$supplierId/edit': {
      id: '/restaurant/suppliers/$supplierId/edit'
      path: '/edit'
      fullPath: '/restaurant/suppliers/$supplierId/edit'
      preLoaderRoute: typeof RestaurantSuppliersSupplierIdEditRouteImport
      parentRoute: typeof RestaurantSuppliersSupplierIdRoute
    }
    '/farmer/stock/movement/new': {
      id: '/farmer/stock/movement/new'
      path: '/movement/new'
      fullPath: '/farmer/stock/movement/new'
      preLoaderRoute: typeof FarmerStockMovementNewRouteImport
      parentRoute: typeof FarmerStockRoute
    }
    '/farmer/stock/$productId/history': {
      id: '/farmer/stock/$productId/history'
      path: '/$productId/history'
      fullPath: '/farmer/stock/$productId/history'
      preLoaderRoute: typeof FarmerStockProductIdHistoryRouteImport
      parentRoute: typeof FarmerStockRoute
    }
    '/farmer/products/$productId/edit': {
      id: '/farmer/products/$productId/edit'
      path: '/edit'
      fullPath: '/farmer/products/$productId/edit'
      preLoaderRoute: typeof FarmerProductsProductIdEditRouteImport
      parentRoute: typeof FarmerProductsProductIdRoute
    }
    '/farmer/orders/$orderId/report': {
      id: '/farmer/orders/$orderId/report'
      path: '/report'
      fullPath: '/farmer/orders/$orderId/report'
      preLoaderRoute: typeof FarmerOrdersOrderIdReportRouteImport
      parentRoute: typeof FarmerOrdersOrderIdRoute
    }
    '/farmer/orders/$orderId/refuse': {
      id: '/farmer/orders/$orderId/refuse'
      path: '/refuse'
      fullPath: '/farmer/orders/$orderId/refuse'
      preLoaderRoute: typeof FarmerOrdersOrderIdRefuseRouteImport
      parentRoute: typeof FarmerOrdersOrderIdRoute
    }
  }
}

interface DriverMissionsRouteChildren {
  DriverMissionsMissionIdRoute: typeof DriverMissionsMissionIdRoute
}

const DriverMissionsRouteChildren: DriverMissionsRouteChildren = {
  DriverMissionsMissionIdRoute: DriverMissionsMissionIdRoute,
}

const DriverMissionsRouteWithChildren = DriverMissionsRoute._addFileChildren(
  DriverMissionsRouteChildren,
)

interface DriverRouteChildren {
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHistoryRoute: typeof DriverHistoryRoute
  DriverMessagesRoute: typeof DriverMessagesRoute
  DriverMissionsRoute: typeof DriverMissionsRouteWithChildren
  DriverNotificationsRoute: typeof DriverNotificationsRoute
  DriverVehicleRoute: typeof DriverVehicleRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverDashboardRoute: DriverDashboardRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHistoryRoute: DriverHistoryRoute,
  DriverMessagesRoute: DriverMessagesRoute,
  DriverMissionsRoute: DriverMissionsRouteWithChildren,
  DriverNotificationsRoute: DriverNotificationsRoute,
  DriverVehicleRoute: DriverVehicleRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface FarmerOrdersOrderIdRouteChildren {
  FarmerOrdersOrderIdRefuseRoute: typeof FarmerOrdersOrderIdRefuseRoute
  FarmerOrdersOrderIdReportRoute: typeof FarmerOrdersOrderIdReportRoute
}

const FarmerOrdersOrderIdRouteChildren: FarmerOrdersOrderIdRouteChildren = {
  FarmerOrdersOrderIdRefuseRoute: FarmerOrdersOrderIdRefuseRoute,
  FarmerOrdersOrderIdReportRoute: FarmerOrdersOrderIdReportRoute,
}

const FarmerOrdersOrderIdRouteWithChildren =
  FarmerOrdersOrderIdRoute._addFileChildren(FarmerOrdersOrderIdRouteChildren)

interface FarmerOrdersRouteChildren {
  FarmerOrdersOrderIdRoute: typeof FarmerOrdersOrderIdRouteWithChildren
}

const FarmerOrdersRouteChildren: FarmerOrdersRouteChildren = {
  FarmerOrdersOrderIdRoute: FarmerOrdersOrderIdRouteWithChildren,
}

const FarmerOrdersRouteWithChildren = FarmerOrdersRoute._addFileChildren(
  FarmerOrdersRouteChildren,
)

interface FarmerProductsProductIdRouteChildren {
  FarmerProductsProductIdEditRoute: typeof FarmerProductsProductIdEditRoute
}

const FarmerProductsProductIdRouteChildren: FarmerProductsProductIdRouteChildren =
  {
    FarmerProductsProductIdEditRoute: FarmerProductsProductIdEditRoute,
  }

const FarmerProductsProductIdRouteWithChildren =
  FarmerProductsProductIdRoute._addFileChildren(
    FarmerProductsProductIdRouteChildren,
  )

interface FarmerProductsRouteChildren {
  FarmerProductsProductIdRoute: typeof FarmerProductsProductIdRouteWithChildren
  FarmerProductsImportRoute: typeof FarmerProductsImportRoute
  FarmerProductsNewRoute: typeof FarmerProductsNewRoute
}

const FarmerProductsRouteChildren: FarmerProductsRouteChildren = {
  FarmerProductsProductIdRoute: FarmerProductsProductIdRouteWithChildren,
  FarmerProductsImportRoute: FarmerProductsImportRoute,
  FarmerProductsNewRoute: FarmerProductsNewRoute,
}

const FarmerProductsRouteWithChildren = FarmerProductsRoute._addFileChildren(
  FarmerProductsRouteChildren,
)

interface FarmerRevenueRouteChildren {
  FarmerRevenueTxIdRoute: typeof FarmerRevenueTxIdRoute
  FarmerRevenueWithdrawRoute: typeof FarmerRevenueWithdrawRoute
  FarmerRevenueWithdrawalsRoute: typeof FarmerRevenueWithdrawalsRoute
}

const FarmerRevenueRouteChildren: FarmerRevenueRouteChildren = {
  FarmerRevenueTxIdRoute: FarmerRevenueTxIdRoute,
  FarmerRevenueWithdrawRoute: FarmerRevenueWithdrawRoute,
  FarmerRevenueWithdrawalsRoute: FarmerRevenueWithdrawalsRoute,
}

const FarmerRevenueRouteWithChildren = FarmerRevenueRoute._addFileChildren(
  FarmerRevenueRouteChildren,
)

interface FarmerStockRouteChildren {
  FarmerStockInventoryRoute: typeof FarmerStockInventoryRoute
  FarmerStockProductIdHistoryRoute: typeof FarmerStockProductIdHistoryRoute
  FarmerStockMovementNewRoute: typeof FarmerStockMovementNewRoute
}

const FarmerStockRouteChildren: FarmerStockRouteChildren = {
  FarmerStockInventoryRoute: FarmerStockInventoryRoute,
  FarmerStockProductIdHistoryRoute: FarmerStockProductIdHistoryRoute,
  FarmerStockMovementNewRoute: FarmerStockMovementNewRoute,
}

const FarmerStockRouteWithChildren = FarmerStockRoute._addFileChildren(
  FarmerStockRouteChildren,
)

interface FarmerRouteChildren {
  FarmerAnalyticsRoute: typeof FarmerAnalyticsRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  FarmerMessagesRoute: typeof FarmerMessagesRoute
  FarmerNotificationsRoute: typeof FarmerNotificationsRoute
  FarmerOrdersRoute: typeof FarmerOrdersRouteWithChildren
  FarmerProductsRoute: typeof FarmerProductsRouteWithChildren
  FarmerRevenueRoute: typeof FarmerRevenueRouteWithChildren
  FarmerSettingsRoute: typeof FarmerSettingsRoute
  FarmerStockRoute: typeof FarmerStockRouteWithChildren
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerAnalyticsRoute: FarmerAnalyticsRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  FarmerMessagesRoute: FarmerMessagesRoute,
  FarmerNotificationsRoute: FarmerNotificationsRoute,
  FarmerOrdersRoute: FarmerOrdersRouteWithChildren,
  FarmerProductsRoute: FarmerProductsRouteWithChildren,
  FarmerRevenueRoute: FarmerRevenueRouteWithChildren,
  FarmerSettingsRoute: FarmerSettingsRoute,
  FarmerStockRoute: FarmerStockRouteWithChildren,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface RestaurantInvoicesRouteChildren {
  RestaurantInvoicesInvoiceIdRoute: typeof RestaurantInvoicesInvoiceIdRoute
}

const RestaurantInvoicesRouteChildren: RestaurantInvoicesRouteChildren = {
  RestaurantInvoicesInvoiceIdRoute: RestaurantInvoicesInvoiceIdRoute,
}

const RestaurantInvoicesRouteWithChildren =
  RestaurantInvoicesRoute._addFileChildren(RestaurantInvoicesRouteChildren)

interface RestaurantMarketplaceRouteChildren {
  RestaurantMarketplaceProductIdRoute: typeof RestaurantMarketplaceProductIdRoute
}

const RestaurantMarketplaceRouteChildren: RestaurantMarketplaceRouteChildren = {
  RestaurantMarketplaceProductIdRoute: RestaurantMarketplaceProductIdRoute,
}

const RestaurantMarketplaceRouteWithChildren =
  RestaurantMarketplaceRoute._addFileChildren(
    RestaurantMarketplaceRouteChildren,
  )

interface RestaurantOrdersRouteChildren {
  RestaurantOrdersOrderIdRoute: typeof RestaurantOrdersOrderIdRoute
}

const RestaurantOrdersRouteChildren: RestaurantOrdersRouteChildren = {
  RestaurantOrdersOrderIdRoute: RestaurantOrdersOrderIdRoute,
}

const RestaurantOrdersRouteWithChildren =
  RestaurantOrdersRoute._addFileChildren(RestaurantOrdersRouteChildren)

interface RestaurantSuppliersSupplierIdRouteChildren {
  RestaurantSuppliersSupplierIdEditRoute: typeof RestaurantSuppliersSupplierIdEditRoute
}

const RestaurantSuppliersSupplierIdRouteChildren: RestaurantSuppliersSupplierIdRouteChildren =
  {
    RestaurantSuppliersSupplierIdEditRoute:
      RestaurantSuppliersSupplierIdEditRoute,
  }

const RestaurantSuppliersSupplierIdRouteWithChildren =
  RestaurantSuppliersSupplierIdRoute._addFileChildren(
    RestaurantSuppliersSupplierIdRouteChildren,
  )

interface RestaurantSuppliersRouteChildren {
  RestaurantSuppliersSupplierIdRoute: typeof RestaurantSuppliersSupplierIdRouteWithChildren
  RestaurantSuppliersNewRoute: typeof RestaurantSuppliersNewRoute
}

const RestaurantSuppliersRouteChildren: RestaurantSuppliersRouteChildren = {
  RestaurantSuppliersSupplierIdRoute:
    RestaurantSuppliersSupplierIdRouteWithChildren,
  RestaurantSuppliersNewRoute: RestaurantSuppliersNewRoute,
}

const RestaurantSuppliersRouteWithChildren =
  RestaurantSuppliersRoute._addFileChildren(RestaurantSuppliersRouteChildren)

interface RestaurantRouteChildren {
  RestaurantCartRoute: typeof RestaurantCartRoute
  RestaurantCheckoutRoute: typeof RestaurantCheckoutRoute
  RestaurantDashboardRoute: typeof RestaurantDashboardRoute
  RestaurantInvoicesRoute: typeof RestaurantInvoicesRouteWithChildren
  RestaurantMarketplaceRoute: typeof RestaurantMarketplaceRouteWithChildren
  RestaurantMessagesRoute: typeof RestaurantMessagesRoute
  RestaurantNotificationsRoute: typeof RestaurantNotificationsRoute
  RestaurantOrdersRoute: typeof RestaurantOrdersRouteWithChildren
  RestaurantRecurringRoute: typeof RestaurantRecurringRoute
  RestaurantSettingsRoute: typeof RestaurantSettingsRoute
  RestaurantSuppliersRoute: typeof RestaurantSuppliersRouteWithChildren
}

const RestaurantRouteChildren: RestaurantRouteChildren = {
  RestaurantCartRoute: RestaurantCartRoute,
  RestaurantCheckoutRoute: RestaurantCheckoutRoute,
  RestaurantDashboardRoute: RestaurantDashboardRoute,
  RestaurantInvoicesRoute: RestaurantInvoicesRouteWithChildren,
  RestaurantMarketplaceRoute: RestaurantMarketplaceRouteWithChildren,
  RestaurantMessagesRoute: RestaurantMessagesRoute,
  RestaurantNotificationsRoute: RestaurantNotificationsRoute,
  RestaurantOrdersRoute: RestaurantOrdersRouteWithChildren,
  RestaurantRecurringRoute: RestaurantRecurringRoute,
  RestaurantSettingsRoute: RestaurantSettingsRoute,
  RestaurantSuppliersRoute: RestaurantSuppliersRouteWithChildren,
}

const RestaurantRouteWithChildren = RestaurantRoute._addFileChildren(
  RestaurantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriverRoute: DriverRouteWithChildren,
  FarmerRoute: FarmerRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantRoute: RestaurantRouteWithChildren,
  TrackPublicIdRoute: TrackPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
